<section class="add">
<?php
$title = 'Add Group';
$this->headTitle ( $title );
?>
 
 <h2><?php echo $this->escapeHtml($title); ?></h2>

<?php if($this->error): ?>
<p class="error">There were one or more issues with your submission.
		Please correct...</p>
<?php endif ?>

<?php

$form = $this->form;
$form->setAttribute ( 'action', $this->url );
$form->prepare ();

echo $this->form ()->openTag ( $form );

foreach ( $form as $element ) :
	?>

<div
		class="control-group <?php
	
	if ($this->formElementErrors ( $element ))
		echo "error"?>">
		<label class="control-label"><?php echo $element->getLabel() ?></label>
		<div class="controls">
        <?php
	
	echo $this->formElement ( $element );
	if ($this->formElementErrors ( $element ))
		?>
                    <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
		</div>
	</div>

<?php
endforeach
;

echo $this->form ()->closeTag ( $form );
?>

</section>