<section class="list">
    <?php
    $title = 'List ' . $this->title;
    $this->headTitle('SIGERI - ' . $title);
    ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3><?php echo $this->escapeHtml($title); ?></h3>
        </div>
        <div class="panel-body">
            <p>
                <a href="<?php echo $this->url($this->router, array('action' => 'add')); ?>">Add
                    new register</a> 
            </p>          