
<section class="delete">

    <?php
    $title = 'Delete ' . $this->title;
    $this->headTitle('SIGERI - ' . $title);
    ?>
    <div class="panel panel-danger">
        <div class="panel-heading">
            <h3><?php echo $this->escapeHtml($title); ?></h3>
        </div>
        <div class="panel-body">
            <p>Are you sure that you want to delete?</p>
            <label>ID:</label> <?php echo $this->escapeHtml($dbArray->getId()); ?> <br>
            <label>Value:</label> <?php echo $this->escapeHtml($dbArray->getValue()); ?> <br>
            <label>Description:</label> <?php echo $this->escapeHtml($dbArray->getDescription()); ?>
            </p>
            </p>
            <?php
            $url = $this->url($this->router, array(
                'action' => 'delete',
                'id' => $this->id
            ));
            ?>
            <form action="<?php echo $url; ?>" method="post" >
                <div class="form-group" >
                    <input  type="hidden" name="id"
                            value="<?php echo (int) $dbArray->getId(); ?>" /> 
                    <input class="btn btn-warning" style="width:100px" type="submit" name="del" 
                           value="Yes" /> 
                    <input class="btn btn-primary" style="width:100px" type="submit"
                           name="del" value="No" />
                </div>
            </form>
        </div>
    </div>
</section>