<?php echo $this->partial('partial/add_top.phtml'); ?>

<?php
foreach ($form as $element) :
                if (!(in_array($element->getAttribute('name'), array('submit', 'description', 'documents')))) {
                    ?>

                    <div class="form-group <?php
                    if ($this->formElementErrors($element))
                        echo "error"
                        ?>">
                        <label class="col-sm-2 control-label"><?php echo $element->getLabel() ?></label>
                        <div class="col-sm-10">
                            <?php
                            //echo $element->getAttribute('type');
                            if ($element->getAttribute('type') != 'submit') {
                                $element->setAttribute('class', 'form-control ' . $element->getAttribute('class'));
                            } else {
                                $element->setAttribute('class', 'btn btn-primary');
                                $element->setAttribute('style', 'width:150px');
                            };

                            //if (!$element->hasAttribute('class'))
                            //	$element->setAttribute('class', 'form-control');
                            echo $this->formElement($element);
                            if ($this->formElementErrors($element))
                                
                                ?>
                            <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
                        </div>
                    </div>

                    <?php
                }
            endforeach;
            ?>
            <br>
            <ul class = "nav nav-tabs nav-justified" style = "color:#000;font-weight: bold;">
                <li class = "active"><a data-toggle = "tab" href = "#description">Description</a></li>
                <li><a data-toggle = "tab" href = "#documents">Documents</a></li>
            </ul>
            <div class = "panel" style = "padding-top:5px;">
                <div class = "tab-content ">
                    <div id = "description" class = "tab-pane fade in active">
                        <?php echo $this->formElement($form->get('description'));
                        ?>
                    </div>
                    <div id = "documents" class = "tab-pane fade in">
                        <?php echo $this->formElement($form->get('documents'));
                        ?>
                    </div>
                </div>
            </div>
            <?php $element = $this->form->get('submit'); ?>
            <div class="form-group" style="text-align:right;">
                <div class="col-sm-12">
                    <?php
                    $element->setAttribute('class', 'btn btn-primary');
                    $element->setAttribute('style', 'width:150px');

                    echo $this->formElement($element);
                    ?>
                </div>
            </div>

            ?> 
<?php echo $this->partial('partial/add_bottom.phtml'); ?>