<section class="list">
    <?php
    $title = $this->escapeHtml($dbArray->getName());
    $this->headTitle('SIGERI - ' . $title);
    ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3><?php echo $this->escapeHtml($title); ?></h3>
        </div>
        <div class="panel-body">
            <p><a href="<?php echo $this->url($this->router, array('action' => 'edit', 'id' => $dbArray->getId())); ?>">
                    Edit register</a> 
            </p>

            <p><label>ID: </label> <?php echo $this->escapeHtml($dbArray->getId()); ?></p> 



            <ul class="nav nav-tabs nav-justified" style="color:#000;font-weight: bold;">
                <li class="active"><a data-toggle="tab" href="#description">Description</a></li>
                <li><a data-toggle="tab" href="#documents">Documents</a></li>                
                <li><a data-toggle="tab" href="#rules">Rules</a></li> 
            </ul>
            <div class="panel" style="padding-top:5px;">

                <div class="tab-content col-sm-12">
                    <div id="description" class="tab-pane fade in active">
                        <p><?php echo $dbArray->getDescription(); ?></p>
                    </div>
                    <div id="documents" class="tab-pane fade in">
                        <p>&nbsp;
                        </p>
                        <table id="datatable" class="table table-striped responsive-utilities jambo_table bulk_action">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Name</th>
                                    <th>Description</th>
                                    <th>Folder</th>
                                    <th>Type</th> 
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($dbArray->getDocuments() as $dbRow) : ?>
                                    <tr>
                                        <td><?php echo $this->escapeHtml($dbRow->getId()); ?></td>
                                        <td><?php echo $this->escapeHtml($dbRow->getName()); ?></td>
                                        <td><?php echo $this->escapeHtml($dbRow->getDescription()); ?></td>
                                        <td><?php echo $this->escapeHtml($dbRow->getFolder()); ?></td>
                                        <td><?php echo $this->escapeHtml($dbRow->getType()); ?></td>                                
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>    
                    <div id = "rules" class = "tab-pane fade in">
                        <div id = "revisions" class = "tab-pane fade in">                            
                            <table id="datatable" class="table table-striped responsive-utilities jambo_table bulk_action">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Rule</th>
                                        <th>Type</th> 
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($dbArray->getRules() as $dbRow) : ?>
                                        <tr>
                                            <td><?php echo $this->escapeHtml($dbRow->getId()); ?></td>
                                            <td><?php echo $this->escapeHtml($dbRow->getRule()); ?></td>
                                            <td><?php echo $this->escapeHtml($dbRow->getType()); ?></td>
                                            
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>

            </div>
        </div>
</section>


<script>

    $(document).ready(function () {
        var table = $('.table').DataTable({
            "lengthChange": false,
            "pagingType": "simple",
            "pageLength": 10,
            "searching": false
        });

    });
</script>