<?php echo $this->partial('partial/view_top.phtml'); ?>
<div class="panel-body">
    <p><label>ID: </label> <?php echo $this->escapeHtml($dbArray->getId()); ?></p> 
    <p><label>Name: </label> <?php echo $this->escapeHtml($dbArray->getName()); ?></p>
    <ul class="nav nav-tabs nav-justified" style="color:#000;font-weight: bold;">
        <li class="active"><a data-toggle="tab" href="#description">Description</a></li>                
        <li><a data-toggle="tab" href="#rules">Rules</a></li> 
        <li><a data-toggle="tab" href="#documents">Documents</a></li>
    </ul>
    <div class="panel" style="padding-top:5px;">

        <div class="tab-content col-sm-12">
            <div id="description" class="tab-pane fade in active">                
                <p><?php echo $dbArray->getDescription(); ?></p>
            </div>
            <div id="documents" class="tab-pane fade in">
                <?php echo $this->partial('partial/list_documents.phtml'); ?>
            </div>    
            <div id = "rules" class = "tab-pane fade in">
                <div id = "revisions" class = "tab-pane fade in">                            
                    <table id="datatable" class="table table-striped responsive-utilities jambo_table bulk_action">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Rule</th>
                                <th>Type</th> 
                                <th></th> 
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($dbArray->getRules() as $dbRow) : ?>
                                <tr>
                                    <td><?php echo $this->escapeHtml($dbRow->getId()); ?></td>
                                    <td><?php echo $this->escapeHtml($dbRow->getName()); ?></td>
                                    <td><?php echo $this->escapeHtml($dbRow->getType()); ?></td>
                                    <td><a
                                        href="<?php
                                        echo $this->url('compliancerule', array(
                                            'action' => 'view',
                                            'id' => $dbRow->getId()
                                        ));
                                        ?>">View</a>
                                    <a
                                        href="<?php
                                        echo $this->url('compliancerule', array(
                                            'action' => 'edit',
                                            'id' => $dbRow->getId()
                                        ));
                                        ?>">Edit</a>
                                    <a
                                        href="<?php
                                        echo $this->url('compliancerule', array(
                                            'action' => 'delete',
                                            'id' => $dbRow->getId()
                                        ));
                                        ?>">Del</a>
                                </td>

                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>

            </div>
        </div>

    </div>
</div>
<?php echo $this->partial('partial/view_bottom.phtml'); ?>