<section class="list">
    <?php
    $title = $this->escapeHtml($dbArray->getName());
    $this->headTitle('SIGERI - ' . $title);
    ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3><?php echo $this->escapeHtml($title); ?></h3>
        </div>
        <div class="panel-body">
            <p><a href="<?php echo $this->url($this->router, array('action' => 'edit', 'id' => $dbArray->getId())); ?>">                    Edit register</a> 
            </p>

            <p><label>ID: </label> <?php echo $this->escapeHtml($dbArray->getId()); ?></p>   
            <p><label>Name: </label> <?php echo $this->escapeHtml($dbArray->getName()); ?></p>
            <p><label>Type: </label> <?php echo $this->escapeHtml($dbArray->getType()); ?></p>
            <p><label>Unit: </label> <?php echo $this->escapeHtml($dbArray->getUnit()); ?></p>
            <p><label>Analyst: </label> <?php echo $this->escapeHtml($dbArray->getAnalyst()); ?></p>

            <br>
            <ul class = "nav nav-tabs nav-justified" style = "color:#000;font-weight: bold;">
                <li class = "active"><a data-toggle = "tab" href = "#description">Description</a></li>
                <li><a data-toggle = "tab" href = "#risks">Risks</a></li>
                <li><a data-toggle = "tab" href = "#vulnerabilities">Vulnerabilities</a></li>
                <li><a data-toggle = "tab" href = "#threaties">Threaties</a></li>
                <li><a data-toggle = "tab" href = "#plans">Plans</a></li>
                <li><a data-toggle = "tab" href = "#dependencies">Dependencies</a></li>
                <li><a data-toggle = "tab" href = "#documents">Documents</a></li>

            </ul>
            <div class = "panel" style = "padding-top:5px;">
                <div class = "tab-content ">
                    <div id = "description" class = "tab-pane fade in active">
                        <p><?php echo $dbArray->getDescription(); ?></p>
                    </div>
                    <div id = "risks" class = "tab-pane fade in">
                        
                    </div>
                    <div id = "vulnerabilities" class = "tab-pane fade in">
                        
                    </div>
                    <div id = "threaties" class = "tab-pane fade in">
                        
                    </div>
                    <div id = "plans" class = "tab-pane fade in">
                        
                    </div>
                    <div id = "dependencies" class = "tab-pane fade in">
                        
                    </div>
                    <div id = "documents" class = "tab-pane fade in">
                        <table id="datatable" class="display table">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Name</th>
                                    <th>Description</th>
                                    <th>Folder</th>
                                    <th>Type</th> 
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($dbArray->getDocuments() as $dbRow) : ?>
                                    <tr>
                                        <td><?php echo $this->escapeHtml($dbRow->getId()); ?></td>
                                        <td><?php echo $this->escapeHtml($dbRow->getName()); ?></td>
                                        <td><?php echo $this->escapeHtml($dbRow->getDescription()); ?></td>
                                        <td><?php echo $this->escapeHtml($dbRow->getFolder()); ?></td>
                                        <td><?php echo $this->escapeHtml($dbRow->getType()); ?></td>                                
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>   

                </div>
            </div>
        </div>
    </div>

</section>

<script>

    $(document).ready(function () {
        var table = $('#datatable').DataTable({
            "lengthChange": false,
            "pagingType": "simple",
            "pageLength": 10,
            "searching": false
        });

    });
</script>