<?php echo $this->partial('partial/add_top.phtml'); ?>
<?php
foreach ($form as $element) :
    if ((in_array($element->getAttribute('name'), array('name', 'status', 'type', 'likelihood', 'impact', 'analyst')))) {
        ?>
        <div class="form-group <?php
        if ($this->formElementErrors($element))
            echo "error"
            ?>">
            <label class="col-xs-2 col-sm-2 col-md-2 control-label"><?php echo $element->getLabel() ?></label>
            <div class="col-xs-10 col-sm-10 col-md-10">
                <?php
                $element->setAttribute('class', 'form-control ' . $element->getAttribute('class'));

                //if (!$element->hasAttribute('class'))
                //	$element->setAttribute('class', 'form-control');
                echo $this->formElement($element);
                if ($this->formElementErrors($element))
                    
                    ?>
                <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
            </div>
        </div>
        <?php
    }
endforeach;
?>        

<br>
<ul class = "nav nav-tabs nav-justified" style = "color:#000;font-weight: bold;">
    <li class = "active"><a data-toggle = "tab" href = "#description">Description</a></li>
    <li><a data-toggle = "tab" href = "#notes">Notes</a></li>
    <li><a data-toggle = "tab" href = "#vulnerabilities">Vulnerabilities</a></li>
    <li><a data-toggle = "tab" href = "#threaties">Threaties</a></li>                        
    <li><a data-toggle = "tab" href = "#controls">Controls</a></li>
    <li><a data-toggle = "tab" href = "#compliance">Compliance</a></li>    
    <li><a data-toggle = "tab" href = "#assets">Assets</a></li>
    <li><a data-toggle = "tab" href = "#documents">Documents</a></li>
</ul>
<div class = "panel" style = "padding-top:5px;">
    <div class = "tab-content ">
        <div id = "description" class = "tab-pane fade in active">
            <?php echo $this->formElement($form->get('description'));
            ?>
        </div>
        <div id = "notes" class = "tab-pane fade in">
            <?php echo $this->formElement($form->get('annotations'));
            ?>
        </div>        
        <div id = "vulnerabilities" class = "tab-pane fade in">
            <?php echo $this->formElement($form->get('vulnerabilities'));
            ?>
        </div>
        <div id = "threaties" class = "tab-pane fade in">
            <?php echo $this->formElement($form->get('threaties'));
            ?>
        </div>        
        <div id = "controls" class = "tab-pane fade in">
            <?php echo $this->formElement($form->get('controls'));
            ?>
        </div>
        <div id = "compliance" class = "tab-pane fade in">
            <?php echo $this->formElement($form->get('compliance'));
            ?>
        </div>
        <div id = "assets" class = "tab-pane fade in">
            <?php echo $this->formElement($form->get('assets'));
            ?>
        </div>
        <div id = "documents" class = "tab-pane fade in">
            <?php echo $this->formElement($form->get('documents'));
            ?>
        </div>
    </div>
</div>
<?php echo $this->partial('partial/add_bottom.phtml'); ?>