<script type="text/javascript" src="/js/mygraph.js"></script>
<link type="text/css" href="/css/mygraph.css" rel="stylesheet">

<?php
echo $this->headScript()
        ->prependFile($this->basePath() . '/js/d3.js')
?>
<section class="edit">            
    <?php
    $title = 'Graphs ' . $this->title;
    $this->headTitle('SIGERI - ' . $title);
    ?>

    <h2><?php echo $this->escapeHtml($title); ?></h2>
    <?php echo $this->data2 ?>
    <div id="multicolumnchart01">          
        <style>
            .column a:visited {
                fill: #CCC;
            }
        </style>

        <script type="text/javascript">
            // columnChart(destiny div, json link, list of fields, external links, labels, yLabel) 
            multicolumnChart("multicolumnchart01", "/risk/jsonRiskData", ["impact", "likelihood"], "/risk/view/", 1, "likelihood x impact");
        </script>
    </div>
</section>
