<?php echo $this->partial('partial/delete_top.phtml'); ?>
<div class="panel-body">
    <p>Are you sure that you want to delete?</p>
    Name: <?php echo $this->escapeHtml($dbArray->getName()); ?> <br>
    Type: <?php echo $this->escapeHtml($dbArray->getType()); ?> <br>
    Analyst: <?php echo $this->escapeHtml($dbArray->getAnalyst()); ?> <br>
    Registered: <?php echo $this->dateFormat($dbArray->getCreated(), IntlDateFormatter::LONG); ?><br>
    Updated: <?php echo $this->dateFormat($dbArray->getUpdated(), IntlDateFormatter::LONG); ?>  

    <?php echo $this->partial('partial/delete_bottom.phtml'); 