<?php echo $this->partial('partial/edit_top.phtml'); ?>
<?php
foreach ($form as $element) :
    if ((in_array($element->getAttribute('name'), array('name', 'status', 'type', 'likelihood', 'impact', 'analyst', 'date')))) {
        ?>
        <div class="form-group <?php
        if ($this->formElementErrors($element))
            echo "error"
            ?>">
            <label class="col-xs-2 col-sm-2 col-md-2 control-label"><?php echo $element->getLabel() ?></label>
            <div class="col-xs-10 col-sm-10 col-md-10">
                <?php
                $element->setAttribute('class', 'form-control ' . $element->getAttribute('class'));

                //if (!$element->hasAttribute('class'))
                //	$element->setAttribute('class', 'form-control');
                echo $this->formElement($element);
                if ($this->formElementErrors($element))
                    
                    ?>
                <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
            </div>
        </div>
        <?php
    }
endforeach;
?>                        

<br>
<ul class = "nav nav-tabs nav-justified" style = "color:#000;font-weight: bold;">
    <li class = "active"><a data-toggle = "tab" href = "#description">Description</a></li>
    <li><a data-toggle = "tab" href = "#notes">Notes</a></li>
    <li><a data-toggle = "tab" href = "#vulnerabilities">Vulnerabilities</a></li>
    <li><a data-toggle = "tab" href = "#threaties">Threaties</a></li>                        
    <li><a data-toggle = "tab" href = "#controls">Controls</a></li>
    <li><a data-toggle = "tab" href = "#compliance">Compliance</a></li>    
    <li><a data-toggle = "tab" href = "#assets">Assets</a></li>
    <li><a data-toggle = "tab" href = "#documents">Documents</a></li>
    <li><a data-toggle = "tab" href = "#method">Method</a></li>
    <li><a data-toggle = "tab" href = "#revisions">Revisions</a></li>
</ul>
<div class = "panel" style = "padding-top:5px;">
    <div class = "tab-content ">
        <div id = "description" class = "tab-pane fade in active">
            <?php echo $this->formElement($form->get('description'));
            ?>
        </div>
        <div id = "notes" class = "tab-pane fade in">
            <?php echo $this->formElement($form->get('annotations'));
            ?>
        </div>        
        <div id = "vulnerabilities" class = "tab-pane fade in">
            <?php echo $this->formElement($form->get('vulnerabilities'));
            ?>
        </div>
        <div id = "threaties" class = "tab-pane fade in">
            <?php echo $this->formElement($form->get('threaties'));
            ?>
        </div>        
        <div id = "controls" class = "tab-pane fade in">
            <?php echo $this->formElement($form->get('controls'));
            ?>
        </div>
        <div id = "compliance" class = "tab-pane fade in">
            <?php echo $this->formElement($form->get('compliance'));
            ?>
        </div>
        <div id = "assets" class = "tab-pane fade in">
            <?php echo $this->formElement($form->get('assets'));
            ?>
        </div>
        <div id = "documents" class = "tab-pane fade in">
            <?php echo $this->formElement($form->get('documents'));
            ?>
        </div>
        <div id = "revisions" class = "tab-pane fade in">
            <p>
                <a href="<?php
                echo $this->url('riskreview', array('action' => 'add'), array('query' => array('risk_id' => $dbArray->getId()))
                );
                ?>">
                    New revision register</a> 
            </p>
            <table id="datatable" class="display table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Status</th>                
                        <th>Analyst</th>
                        <th>Register</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($dbArray->getRevisions() as $dbRow) : ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($dbRow->getId()); ?></td>
                            <td><?php echo $this->escapeHtml($dbRow->getName()); ?></td>
                            <td><?php echo $this->escapeHtml($dbRow->getStatus()); ?></td>
                            <td><?php echo $this->escapeHtml($dbRow->getAnalyst()); ?></td>
                            <td><?php echo $this->escapeHtml($dbRow->getFormatedDate()); ?></td>
                            <td><a
                                    href="<?php
                                    echo $this->url('riskreview', array(
                                        'action' => 'edit',
                                        'id' => $dbRow->getId()
                                    ));
                                    ?>">Edit</a>
                                <a
                                    href="<?php
                                    echo $this->url('riskreview', array(
                                        'action' => 'delete',
                                        'id' => $dbRow->getId()
                                    ));
                                    ?>">Del</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>


        </div>
        <div id = "method" class = "tab-pane fade in">
            <!-- HTML and script to redirect to another page based on the select -->
            <div class="form-group" style="padding-right:15px; padding-left: 15px;">
                <select id="method" class="form-control">
                    <option value="methodclassic">Add Classic Calculation</option>
                    <option value="methodowasp">Add OWASP Calculation</option>
                    <option value="methodcvss">Add CVSS Calculation</option>
                    <option value="methodoctave">Add Octave Calculation</option>
                </select>
            </div>
            <script type="text/javascript">
                $(document).ready(function () {
                    $('select#method').on('click', function () {
                        $(location).attr('href', '/' + $(this).val() + '/add?risk_id=' + <?php echo $dbArray->getId(); ?> + '');
                    });
                });

            </script>
            <!-- HTML and script to redirect to another page based on the select -->

            <table id="datatable" class="display table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Method</th>
                        <th>Value</th>                
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($dbArray->getMethod() as $dbRow) : ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($dbRow->getId()); ?></td>
                            <td><?php echo strtoupper($this->escapeHtml($dbRow->getMethod())); ?></td>
                            <td><?php echo $this->escapeHtml($dbRow->getValue()); ?></td>
                            <td><a
                                    href="<?php
                                    echo $this->url('method' . $dbRow->getMethod(), array(
                                        'action' => 'view',
                                        'id' => $dbRow->getId()
                                    ));
                                    ?>">View</a>
                                <a
                                    href="<?php
                                    echo $this->url('method' . $dbRow->getMethod(), array(
                                        'action' => 'edit',
                                        'id' => $dbRow->getId()
                                    ));
                                    ?>">Edit</a>
                                <a
                                    href="<?php
                                    echo $this->url('method' . $dbRow->getMethod(), array(
                                        'action' => 'delete',
                                        'id' => $dbRow->getId()
                                    ));
                                    ?>">Del</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?php echo $this->partial('partial/edit_bottom.phtml'); ?>

