<section class="list">
    <?php
    $title = 'List ' . $this->title;
    $this->headTitle('SIGERI - ' . $title);
    ?>

    <h2><?php echo $this->escapeHtml($title); ?></h2>
    <p>
        <a href="<?php echo $this->url($this->router, array('action' => 'add')); ?>">Add
            new register</a> |
        <a href="<?php echo $this->url($this->router, array('action' => 'chart')); ?>">View 
            Chart Risk</a>
    </p>

    <table id="datatable" class="display table">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Impact</th>
            <th>Probability</th>
            <th>Vulnerability</th>
            <th>Threat</th>
            <th>Type</th>
            <th>Analyst</th>
            <th>Register</th>
            <th>Description</th>
            <th>&nbsp;</th>
        </tr>
        <?php foreach ($dbArray as $dbRow) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($dbRow->getId()); ?></td>
                <td><?php echo $this->escapeHtml($dbRow->getName()); ?></td>
                <td><?php echo $this->escapeHtml($dbRow->getImpact()); ?></td>
                <td><?php echo $this->escapeHtml($dbRow->getProbability()); ?></td>
                <td><?php echo $this->escapeHtml($dbRow->getVulnerability()); ?></td>
                <td><?php echo $this->escapeHtml($dbRow->getThreat()); ?></td>
                <td><?php echo $this->escapeHtml($dbRow->getType()); ?></td>
                <td><?php echo $this->escapeHtml($dbRow->getAnalyst()); ?></td>
                <td><?php echo $this->escapeHtml($dbRow->getFormatedDate()); ?></td>
                <td><?php echo $this->escapeHtml($dbRow->getDescription()); ?></td>
                <td><a
                        href="<?php
                        echo $this->url($this->router, array(
                            'action' => 'edit',
                            'id' => $dbRow->getId()
                        ));
                        ?>">Edit</a>
                    <a
                        href="<?php
                        echo $this->url($this->router, array(
                            'action' => 'delete',
                            'id' => $dbRow->getId()
                        ));
                        ?>">Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</section>

<script>
    $(document).ready(function(){
    $('#datatable').DataTable();
});
</script>