<section class="list">
    <?php
    $title = 'List ' . $this->title;
    $this->headTitle('SIGERI - ' . $title);
    ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3><?php echo $this->escapeHtml($title); ?></h3>
        </div>
        <div class="panel-body">
            <p>
                <a href="<?php echo $this->url($this->router, array('action' => 'add')); ?>">Add
                    new register</a> |
                <a href="<?php echo $this->url($this->router, array('action' => 'report')); ?>">View 
                    Report Risks</a>
            </p>

            <table id="datatable" class="display table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Impact</th>
                        <th>Probability</th>
                        <th id="risk">Risk</th>
                        <th>Type</th>
                        <th>Analyst</th>
                        <th>Register</th> 
                        <th style="width:120px;">&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($dbArray as $dbRow) : ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($dbRow->getId()); ?></td>
                            <td><?php echo $this->escapeHtml($dbRow->getName()); ?></td>
                            <td><?php echo $this->escapeHtml($dbRow->getImpact()); ?></td>
                            <td><?php echo $this->escapeHtml($dbRow->getProbability()); ?></td>
                            <td><?php echo $this->escapeHtml($dbRow->getImpact()->getValue() * $dbRow->getProbability()->getValue()); ?></td>
                            <td><?php echo $this->escapeHtml($dbRow->getType()); ?></td>
                            <td><?php echo $this->escapeHtml($dbRow->getAnalyst()); ?></td>
                            <td><?php echo $this->escapeHtml($dbRow->getFormatedDate()); ?></td>
                            <td><a
                                    href="<?php
                                    echo $this->url($this->router, array(
                                        'action' => 'view',
                                        'id' => $dbRow->getId()
                                    ));
                                    ?>">View </a>
                                <a
                                    href="<?php
                                    echo $this->url($this->router, array(
                                        'action' => 'edit',
                                        'id' => $dbRow->getId()
                                    ));
                                    ?>">Edit</a>
                                <a
                                    href="<?php
                                    echo $this->url($this->router, array(
                                        'action' => 'delete',
                                        'id' => $dbRow->getId()
                                    ));
                                    ?>">Delete</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</section>

<script>

    $(document).ready(function () {
        var table = $('#datatable').DataTable({
            "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
            "pageLength": 50,
        });

    });



    var colindex = document.getElementById('risk').cellIndex;
    $('#datatable tbody tr td:nth-child(5)').each(function () {
        cell = $(this);
        if (cell.text() < 10) {
            cell.css('background-color', '#88FF88');
        }
        else {
            cell.css('background-color', '#FF8888');
        }
        console.log(cell.text());
    });


//    var dataTbl = document.getElementById('datatable');
//    
//    for (var i = 0; i < dataTbl.rows.length; i++){
//        for (var j=0; j< dataTbl.rows[i].cells.length; j++)
//        console.log(dataTbl.rows[i].cells[j]);
//    }


</script>