<!-- <script src="" type="text/javascript" /> -->
<?php
echo $this->headScript()
        ->prependFile($this->basePath() . '/js/d3.js')
?>
<section class="edit">
    <div class="row">
        <div class="col-md-8">                   
            <?php
            $title = 'Graphs ' . $this->title;
            $this->headTitle('SIGERI - ' . $title);
            ?>

            <h2><?php echo $this->escapeHtml($title); ?></h2>
            <?php echo $this->data2 ?>

            <svg id="matrix"></svg>
            <style></style>
            <script type="text/javascript">
                var width = 720,
                        height = 700;

                var r = 10;
                
                var svg = d3.select("#matrix")
                        .attr("width", width)
                        .attr("height", height)
                        .attr("color", "#EEE");



                d3.json("jsonData", function (data) {

                    var maxX = d3.max(data, function (d) {
                        return d.impact;
                    });

                    var maxY = d3.max(data, function (d) {
                        return d.probability;
                    });

                    var xPos = d3.scale.linear()
                            .domain([0, maxX])
                            .range([0, width]);

                    var yPos = d3.scale.linear()
                            .domain([0, maxY])
                            .range([height, 0]);


                    svg.selectAll("circle")
                            .data(data).enter()
                            .append("circle")
                            .attr("cx", function (d) {
                                console.log(xPos(d.probability));
                                return xPos(d.probability);
                            })
                            .attr("cy", function (d) {
                                console.log(yPos(d.impact));
                                return yPos(d.impact) + r;
                            })
                            .attr("r", function (d) {
                                return r;
                            })
                            .on("click", function (d) {
                                console.log(d.name);
                            })
                            .on("mouseover", function () {
                                d3.select(this)
                                        .attr("fill", "orange");
                            })
                            .on("mouseout", function () {
                                d3.select(this)
                                        .attr("fill", "blue");
                            })
                            .append("svg:title")
                            .text(function (d) {
                                return 'name: ' + d.name + '\n' +
                                        'probability: ' + d.probability + '\n' +
                                        'impact: ' + d.impact;
                            });

                    var xAxis = d3.svg.axis()
                            .scale(xPos)
                            .orient("bottom");

                    svg.append("g")
                            .attr("transform", "translate(0," + (height) + ")")
                            .call(xAxis);

                    var yAxis = d3.svg.axis()
                            .scale(yPos)
                            .orient("right");

                    svg.append("g")
                            .attr("transform", "translate(0 ,0)")
                            .call(yAxis);
                });

            </script>



            <div class="chart"></div>

            <style>
                .chart div {
                    font: 10px sans-serif;
                    background-color: steelblue;
                    text-align: right;
                    padding: 3px;
                    margin: 1px;
                    color: white;
                }
            </style>

            <script type="text/javascript">
                d3.json("jsonData", function (data) {
                    var max_n = 0;
                    for (var d in data) {
                        max_n = Math.max(data[d].probability, max_n);
                    }
                    ;
                    var x = d3.scale.linear()
                            .domain([0, max_n])
                            .range([0, 720]);

                    d3.select(".chart")
                            .selectAll("div")
                            .data(data)
                            .enter().append("div")
                            .style("width", function (d) {
                                return x(d.probability) + "px";
                            })
                            .text(function (d) {
                                return d.name;
                            });
                });</script>

            <p></p>


            <p> ---- </p>


            <svg class="chartbar"></svg>

            <style>

                .chartbar .bar:hover {
                    fill: brown;
                }

                .chartbar .axis text {
                    font: 10px sans-serif;
                }

                .chartbar .axis path, .axis line {
                    fill: none;
                    stroke: #000;
                    shape-rendering: crispEdges;
                }

                .chartbar .x.axis path {          
                    display: none;
                }
            </style>

            <script type="text/javascript">

                var margin = {top: 20, right: 30, bottom: 30, left: 40},
                width = 720 - margin.left - margin.right,
                        height = 400 - margin.top - margin.bottom;

                /*var x = d3.scale.ordinal().rangeRoundBands([0, width], .1);
                 var y = d3.scale.linear().range([height, 0]);
                 
                 var xAxis = d3.svg.axis()
                 .scale(x)
                 .orient("bottom");
                 
                 var yAxis = d3.svg.axis()
                 .scale(y)
                 .orient("left")
                 .ticks(10, "%");
                 */

                var chartbar = d3.select(".chartbar")
                        .attr("width", width + margin.left + margin.right)
                        .attr("height", height + margin.top + margin.bottom)
                        .append("g")
                        .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

                d3.json("jsonData", function (data) {

                    // Convert JSON data to stack format 
                    var stack = d3.layout.stack();

                    var fields = d3.keys(data[0])
                            .filter(function (key) {
                                return (key !== "name" && key !== "id");
                            });

                    var name = data.map(function (d) {
                        return d.name;
                    });

                    var dataset = stack(d3.range(fields.length).map(function (d) {
                        var a = [];
                        for (var i = 0; i < data.length; ++i) {
                            a[i] = {x: i, y: data[i][fields[d]]};
                        }
                        return a;
                    }));


                    var xScale = d3.scale.ordinal()
                            .domain(d3.range(dataset[0].length))
                            .rangeRoundBands([0, width], 0.05);

                    var yScale = d3.scale.linear()
                            .domain([0, d3.max(dataset, function (d) {
                                    return d3.max(d, function (d) {
                                        return d.y0 + d.y;
                                    });
                                })
                            ]).range([0, height]);

                    var colors = d3.scale.category10();

                    // Add a group for each row of data
                    var groups = chartbar.selectAll("g")
                            .data(dataset)
                            .enter()
                            .append("g")
                            .style("fill", function (d, i) {
                                return colors(i);
                            });

                    // Add a rect for each data value
                    var rects = groups.selectAll("rect")
                            .data(function (d) {
                                return d;
                            })
                            .enter()
                            .append("rect")
                            .attr("x", function (d, i) {
                                return xScale(i);
                            })
                            .attr("y", function (d) {
                                return yScale(d.y0);
                            })
                            .attr("height", function (d) {
                                return yScale(d.y);
                            })
                            .attr("width", xScale.rangeBand());

                });

                function type(d) {
                    d.value = +d.value; // coerce to number
                    return d;
                }

            </script>


            <p>----</p>

            <svg class="chartcircle"></svg>

            <style>
                .bar {
                    fill: steelblue;
                }

                .bar:hover {
                    fill: brown;
                }

                .axis text {
                    font: 10px sans-serif;
                }

                .axis path, .axis line {
                    fill: none;
                    stroke: #000;
                    shape-rendering: crispEdges;
                }

                .x.axis path {          
                    display: none;
                }
            </style>

            <script type="text/javascript">

                var margin = {top: 20, right: 30, bottom: 30, left: 40},
                width = 720 - margin.left - margin.right,
                        height = 400 - margin.top - margin.bottom;

                var x = d3.scale.ordinal().rangeRoundBands([0, width], .1);
                var y = d3.scale.linear().range([height, 0]);

                var xAxis = d3.svg.axis()
                        .scale(x)
                        .orient("bottom");

                var yAxis = d3.svg.axis()
                        .scale(y)
                        .orient("left")
                        .ticks(10, "%");

                var chart = d3.select(".chartcircle")
                        .attr("width", width + margin.left + margin.right)
                        .attr("height", height + margin.top + margin.bottom)
                        .append("g")
                        .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

                d3.json("jsonData", function (data) {
                    x.domain(data.map(function (d) {
                        return d.name;
                    }));

                    y.domain([0, d3.max(data, function (d) {
                            return d.impact;
                        })]);

                    chart.append("g")
                            .attr("class", "x axis")
                            .attr("transform", "translate(0," + height + ")")
                            .call(xAxis);

                    chart.append("g")
                            .attr("class", "y axis")
                            .call(yAxis)
                            .append("text")
                            .attr("transform", "rotate(-90)")
                            .attr("y", 6)
                            .attr("dy", ".70em")
                            .style("text-anchor", "end")
                            .text("Frequency");

                    chart.selectAll(".bar")
                            .data(data)
                            .enter().append("a")
                            .attr("xlink:href", function (d) {
                                return "/risk/edit/" + d.id;
                            })
                            .append("rect")
                            .attr("class", "bar")
                            .attr("x", function (d) {
                                return x(d.name);
                            })
                            .attr("y", function (d) {
                                return y(d.impact);
                            })
                            .attr("height", function (d) {
                                return height - y(d.impact);
                            })
                            .attr("width", x.rangeBand())
                            .on("click", function (d) {
                                console.log(d.id);
                            });

                });

                function type(d) {
                    d.value = +d.value; // coerce to number
                    return d;
                }

            </script>




            <!--
            <svg class="chartx"></svg><p>
                                    
            <script type="text/javascript">						
                    var dataset = <?php echo $this->data2 ?>;

                    var w = 720,
                        h = 520,
                        barPadding = 1,
                        n = 2;
                
                var stack = d3.layout.stack();
                var layers = stack(d3.range(n).map(function() { 
                                                    return d3.values(dataset); }));


                dataset.forEach(function (d) {
                      var y0 = 0;
                      d.mapping = d3.range(n).map(function (name) {
                              return {
                                      name: name,
                                      label: d[name],
                                      y0: y0,
                                      y1: y0 += +d[name]};
                              });
                      d.total = d.mapping[d.mapping.length - 1].y1;
                    });
            
                console.log(dataset);

                var x = d3.scale.ordinal()
                    .rangeRoundBands([0, w], .1);

            var y = d3.scale.linear()
                    .rangeRound([h, 0]);

                    //Create SVG element
                    
                    var color = d3.scale.linear()
                        .domain([0, n - 1])
                        .range(["#aad", "#556"]);
            

                    var svg = d3.select(".chartx")
                        .attr("width", w )
                        .attr("height", h )
                        .append("g")
                        .attr("transform", "translate( 10, 10)");;
            
                    var layer = svg.selectAll(".layer")
                        .data(layers)
                        .enter()
                        .append("g")
                        .attr("class", "layer")
                        .style("fill", function(d, i) { return color(i); });

                    var rect = layer.selectAll("rect")
                        .data(function(d) { return d; })
                        .enter()
                        .append("rect")
                        .attr("width", x.rangeBand())
                    .attr("y", function (d) { return y(d.y1); })
                    .attr("height", function (d) { return y(d.y0) - y(d.y1); })

                svg.selectAll("text")
                            .data(dataset)
                            .enter()
                            .append("text")
                            .text(function(d){ return d.name })
                            .attr("x", function(d, i) { return (i * (w / dataset.length ) + (w / dataset.length) / 2)  ; })
                            .attr("y", function(d) {	return h - (d.probability * 1) + 15; })
                            .attr("text-anchor", "middle");
            </script>
            
            <svg class="chart"></svg><p>
                                    
            <script type="text/javascript">						
                    var dataset = <?php echo $this->data2 ?>;

                    var w = 720;
                    var h = 520;
                    var barPadding = 1;

                    //Create SVG element
                    
                    var svg = d3.select(".chart")
                                            .attr("width", w)
                                            .attr("height", h);

                    
                       
                    svg.selectAll("rect")
                       .data(dataset)
                       .enter()
                       
                       .append("rect")
                       .attr("x", function(d, i) { return i * (w / dataset.length); })
                       .attr("y", function(d) {	return h - (d.probability * 1); })
                       .attr("width", w / dataset.length - barPadding)
                       .attr("height", function(d) { return d.probability * 1; })
                       .attr("fill", "brown")
                       
                    svg.selectAll("text")
                            .data(dataset)
                            .enter()
                            .append("text")
                            .text(function(d){ return d.name })
                            .attr("x", function(d, i) { return (i * (w / dataset.length ) + (w / dataset.length) / 2)  ; })
                            .attr("y", function(d) {	return h - (d.probability * 1) + 15; })
                            .attr("text-anchor", "middle");
            </script>
            
            
            <!--<svg class="chart"></svg>
                                    
             <script type="text/javascript">						
                    var dataset = <?php echo $this->data2 ?>;

                    function probability(d){ console.log(d); return d.probability.value; };
                    function threat(d){ console.log(d); return d.threat.value; };
                    //probability(dataset[3]);

                    var w = 520;
                    var h = 550;

                    //Create SVG element
                    var svg = d3.select("body")
                                            .append("svg")
                                            .attr("width", w)
                                            .attr("height", h);

                    var circles = svg.selectAll("circle")
                        .data(dataset)
                        .enter()
                        .append("circle");

                    circles.attr("cx", function(d, i) {
                                            return (i * 100) + 25;
                                    })
                               .attr("cy", h/2)
                               .attr("r", function(d) {
                                        console.log(d.probability.value);
                                            return d.probability.value / 2;
                               });
                    
            </script>
            -->		
            <p>
                <?php //var_dump($this->results);?>

<!-- <svg class="chart2"></svg> 

                <script type="text/javascript">
                    var dataset = <?php echo $this->data ?>;
                    var width = 520;
                    var height = 350;
                    var x = d3.scale.linear()
                            .domain([0, d3.max(dataset["values"])])
                            .range([0, width]);
                    var chart = d3.select(".chart2")
                            .attr("width", width)
                            .attr("height", height);
                    var bar = chart.selectAll("g")
                            .data(dataset["values"])
                            .enter()
                            .append("g")
                            .attr("transform", function (d, i) {
                                return "translate(0," + i * (height / 14) + ")";
                            });
                    var xAxis = d3.svg.axis()
                            .scale(x)
                            .orient("bottom");
                    bar.append("rect")
                            .attr("width", x)
                            .attr("height", (height / 14) - 1)
                            .attr("fill", function (d) {
                                return "rgb(0,150," + (d * 2) + ")";
                            });
                    bar.append("text")
                            .attr("x", function (d) {
                                return x(d) - 3;
                            })
                            .attr("y", function (d) {
                                return (height / 14) / 2
                            })
                            .attr("dy", ".35em")
                            .text(function (d) {
                                return d[0];
                            });
                    chart.append("g")
                            .attr("class", "axis")
                            .attr("transform", "translate(0," + (height - 15) + ")")
                            .call(xAxis);</script>		


            <style>

                body {
                    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                    margin: auto;
                    position: relative;
                    width: 960px;
                }

                text {
                    font: 10px sans-serif;
                }

                .axis path,
                .axis line {
                    fill: none;
                    stroke: #000;
                    shape-rendering: crispEdges;
                }

                form {
                    position: absolute;
                    right: 10px;
                    top: 10px;
                }

            </style>
            <form>
                <label><input type="radio" name="mode" value="grouped"> Grouped</label>
                <label><input type="radio" name="mode" value="stacked" checked> Stacked</label>
            </form>
            <script src="http://d3js.org/d3.v3.min.js"></script>
            <script>

                    var n = 4, // number of layers
                            m = 58, // number of samples per layer
                            stack = d3.layout.stack(),
                            layers = stack(d3.range(n).map(function () {
                                return bumpLayer(m, .1);
                            })),
                            yGroupMax = d3.max(layers, function (layer) {
                                return d3.max(layer, function (d) {
                                    return d.y;
                                });
                            }),
                            yStackMax = d3.max(layers, function (layer) {
                                return d3.max(layer, function (d) {
                                    return d.y0 + d.y;
                                });
                            });
                    console.log(layers);
                    var margin = {top: 40, right: 10, bottom: 20, left: 10},
                    width = 960 - margin.left - margin.right,
                            height = 500 - margin.top - margin.bottom;
                    var x = d3.scale.ordinal()
                            .domain(d3.range(m))
                            .rangeRoundBands([0, width], .08);
                    var y = d3.scale.linear()
                            .domain([0, yStackMax])
                            .range([height, 0]);
                    var color = d3.scale.linear()
                            .domain([0, n - 1])
                            .range(["#aad", "#556"]);
                    var xAxis = d3.svg.axis()
                            .scale(x)
                            .tickSize(0)
                            .tickPadding(6)
                            .orient("bottom");
                    var svg = d3.select("body").append("svg")
                            .attr("width", width + margin.left + margin.right)
                            .attr("height", height + margin.top + margin.bottom)
                            .append("g")
                            .attr("transform", "translate(" + margin.left + "," + margin.top + ")");
                    var layer = svg.selectAll(".layer")
                            .data(layers)
                            .enter().append("g")
                            .attr("class", "layer")
                            .style("fill", function (d, i) {
                                return color(i);
                            });
                    var rect = layer.selectAll("rect")
                            .data(function (d) {
                                return d;
                            })
                            .enter().append("rect")
                            .attr("x", function (d) {
                                return x(d.x);
                            })
                            .attr("y", height)
                            .attr("width", x.rangeBand())
                            .attr("height", 0);
                    rect.transition()
                            .delay(function (d, i) {
                                return i * 10;
                            })
                            .attr("y", function (d) {
                                return y(d.y0 + d.y);
                            })
                            .attr("height", function (d) {
                                return y(d.y0) - y(d.y0 + d.y);
                            });
                    svg.append("g")
                            .attr("class", "x axis")
                            .attr("transform", "translate(0," + height + ")")
                            .call(xAxis);
                    d3.selectAll("input").on("change", change);
                    var timeout = setTimeout(function () {
                        d3.select("input[value=\"grouped\"]").property("checked", true).each(change);
                    }, 2000);
                    function change() {
                        clearTimeout(timeout);
                        if (this.value === "grouped")
                            transitionGrouped();
                        else
                            transitionStacked();
                    }

                    function transitionGrouped() {
                        y.domain([0, yGroupMax]);
                        rect.transition()
                                .duration(500)
                                .delay(function (d, i) {
                                    return i * 10;
                                })
                                .attr("x", function (d, i, j) {
                                    return x(d.x) + x.rangeBand() / n * j;
                                })
                                .attr("width", x.rangeBand() / n)
                                .transition()
                                .attr("y", function (d) {
                                    return y(d.y);
                                })
                                .attr("height", function (d) {
                                    return height - y(d.y);
                                });
                    }

                    function transitionStacked() {
                        y.domain([0, yStackMax]);
                        rect.transition()
                                .duration(500)
                                .delay(function (d, i) {
                                    return i * 10;
                                })
                                .attr("y", function (d) {
                                    return y(d.y0 + d.y);
                                })
                                .attr("height", function (d) {
                                    return y(d.y0) - y(d.y0 + d.y);
                                })
                                .transition()
                                .attr("x", function (d) {
                                    return x(d.x);
                                })
                                .attr("width", x.rangeBand());
                    }

                    // Inspired by Lee Byron's test data generator.
                    function bumpLayer(n, o) {

                        function bump(a) {
                            var x = 1 / (.1 + Math.random()),
                                    y = 2 * Math.random() - .5,
                                    z = 10 / (.1 + Math.random());
                            for (var i = 0; i < n; i++) {
                                var w = (i / n - y) * z;
                                a[i] += x * Math.exp(-w * w);
                            }
                        }

                        var a = [], i;
                        for (i = 0; i < n; ++i)
                            a[i] = o + o * Math.random();
                        for (i = 0; i < 5; ++i)
                            bump(a);
                        return a.map(function (d, i) {
                            return {x: i, y: Math.max(0, d)};
                        });
                    }

            </script>


        </div>
        <div class="col-md-4">
        </div>
    </div>
</section>