<section class="edit">
    <?php
    $title = $this->translate('Edit register') . ': ' . $this->title;
    $this->headTitle('SIGERI - ' . $title);
    ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3><?php echo $this->escapeHtml($title); ?></h3>
        </div>
        <div class="panel-body">
            <?php if ($this->error): ?>
                <p class="error">
                    <?php  echo $this->translate('There were one or more issues with your submission. Please correct...');?>
                </p>
            <?php endif ?>
            <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url);
            $form->setAttribute('class', 'form-horizontal');
            $form->prepare();

            echo $this->form()->openTag($form);
            