<section class="list">
    <?php
    $title = $this->translate('List ') . $this->translate($this->title);
    $this->headTitle('SIGERI - ' . $title);
    ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>
                <?php echo $this->escapeHtml($title); ?>
            <a href="<?php echo $this->url($this->router, array('action' => 'add')); ?>">
                    <button class="btn btn-info" style="float: right;">
                        <?php echo $this->translate('Add new register'); ?>
                    </button>
            </a> 
            </h3>
        </div>
        <div class="panel-body">                   