<section class="list">
    <?php
    $title = 'Review: ' . $this->escapeHtml($dbArray->getName());
    $this->headTitle('SIGERI - ' . $title);
    ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3><?php echo $this->escapeHtml($title); ?></h3>
        </div>
        <div class="panel-body">   

            <p><label>ID: </label> <?php echo $this->escapeHtml($dbArray->getId()); ?></p>
            <p><label>Name: </label> <?php echo $this->escapeHtml($dbArray->getName()); ?></p>
            <p><label>Risk: </label> <?php echo $this->escapeHtml($dbArray->getRisk()); ?></p>
            <p><label>Status: </label> <?php echo $this->escapeHtml($dbArray->getStatus()); ?></p>                
            <p><label>Analyst: </label> <?php echo $this->escapeHtml($dbArray->getAnalyst()); ?></p>
            <p><label>Register: </label> <?php echo $this->escapeHtml($dbArray->getFormatedDate()); ?></p>



            <ul class="nav nav-tabs nav-justified" style="color:#000;font-weight: bold;">
                <li class="active"><a data-toggle="tab" href="#description">Description</a></li>   
            </ul>
            <div class="panel" style="padding-top:5px;">

                <div class="tab-content col-sm-12">
                    <div id="description" class="tab-pane fade in active">
                        <p><?php echo $dbArray->getDescription(); ?></p>
                    </div>

                    <div id="revisions" class="tab-pane fade in">
                        
                    </div>

                </div>
            </div>
        </div>
    </div>

</section>

<script>

    $(document).ready(function () {
        var table = $('#datatable').DataTable({
            "lengthChange": false,
            "pagingType": "simple",
            "pageLength": 10,
            "searching": false
        });

    });
</script>