<?php echo $this->partial('partial/delete_top.phtml'); ?>

<div class="panel-body">
    <p>Are you sure that you want to delete?</p>
    <label>Review:</label> <?php echo $this->escapeHtml($dbArray->getName()); ?> <br>
    <label>Type:</label> <?php echo $this->escapeHtml($dbArray->getType()); ?> <br>
    <label>Analyst:</label> <?php echo $this->escapeHtml($dbArray->getAnalyst()); ?> <br>

    <?php
    echo $this->partial('partial/delete_bottom.phtml');
    