<section class="add">
            <?php
            $title = 'Add ' . $this->title;
            $this->headTitle('SIGERI - ' . $title);
            ?>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3><?php echo $this->escapeHtml($title); ?></h3>
                </div>
                <div class="panel-body">

                    <?php if ($this->error): ?>
                        <p class="error">There were one or more issues with your submission. Please correct...</p>
                    <?php endif ?>

                    <?php
                    $form = $this->form;
                    $form->setAttribute('action', $this->url);
                    $form->setAttribute('class', 'form-horizontal');
                    $form->prepare();

                    echo $this->form()->openTag($form);

                    foreach ($form as $element) :
                        if ((in_array($element->getAttribute('name'), array('name',
                                    'type',
                                    'analyst',
                                    'unit')))) {
                            ?>
                            <div class="form-group <?php
                            if ($this->formElementErrors($element))
                                echo "error"
                                ?>">
                                <label class="col-sm-2 control-label"><?php echo $element->getLabel() ?></label>
                                <div class="col-sm-10">
                                    <?php
                                    $element->setAttribute('class', 'form-control ' . $element->getAttribute('class'));
                                    echo $this->formElement($element);

                                    if ($this->formElementErrors($element))
                                        
                                        ?>
                                    <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
                                </div>
                            </div>

                            <?php
                        }
                    endforeach;
                    
                    foreach ($form as $element) :
                        if ((in_array($element->getAttribute('name'), array('address',
                                    'geolocation')))) {
                            ?>
                            <div class="form-group <?php
                            if ($this->formElementErrors($element))
                                echo "error"
                                ?>">
                                <label class="col-sm-2 control-label"><?php echo $element->getLabel() ?></label>
                                <div class="col-sm-10">
                                    <?php
                                    $element->setAttribute('class', 'form-control ' . $element->getAttribute('class'));
                                    echo $this->formElement($element);

                                    if ($this->formElementErrors($element))
                                        
                                        ?>
                                    <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
                                </div>
                            </div>

                            <?php
                        }
                    endforeach;

                    
                    ?>

                    <br>
                    <ul class = "nav nav-tabs nav-justified" style = "color:#000;font-weight: bold;">
                        <li class = "active"><a data-toggle = "tab" href = "#description">Description</a></li>
                        <li><a data-toggle = "tab" href = "#groups">Groups</a></li>
                        <li><a data-toggle = "tab" href = "#risks">Risks</a></li>
                        <li><a data-toggle = "tab" href = "#vulnerabilities">Vulnerabilities</a></li>
                        <li><a data-toggle = "tab" href = "#threaties">Threaties</a></li>
                        <li><a data-toggle = "tab" href = "#plans">Plans</a></li>
                        <li><a data-toggle = "tab" href = "#dependencies">Dependencies</a></li>
                        <li><a data-toggle = "tab" href = "#documents">Documents</a></li>

                    </ul>
                    <div class = "panel" style = "padding-top:5px;">
                        <div class = "tab-content ">
                            <div id = "description" class = "tab-pane fade in active">
                                <?php echo $this->formElement($form->get('description'));
                                ?>
                            </div>                            
                            <div id = "groups" class = "tab-pane fade in">
                                <?php echo $this->formElement($form->get('groups'));
                                ?>
                            </div>
                            <div id = "risks" class = "tab-pane fade in">
                                <?php echo $this->formElement($form->get('risks'));
                                ?>
                            </div>
                            <div id = "vulnerabilities" class = "tab-pane fade in">
                                <?php echo $this->formElement($form->get('vulnerabilities'));
                                ?>
                            </div>
                            <div id = "threaties" class = "tab-pane fade in">
                                <?php echo $this->formElement($form->get('threaties'));
                                ?>
                            </div>
                            <div id = "plans" class = "tab-pane fade in">
                                <?php echo $this->formElement($form->get('plans'));
                                ?>
                            </div>
                            <div id = "dependencies" class = "tab-pane fade in">
                                <?php echo $this->formElement($form->get('dependencies'));
                                ?>
                            </div>
                            <div id = "documents" class = "tab-pane fade in">
                                <?php echo $this->formElement($form->get('documents'));
                                ?>
                            </div>   

                        </div>
                    </div>
                    <?php $element = $this->form->get('submit'); ?>
                    <div class="form-group" style="text-align:right;">
                        <div class="col-sm-12">
                            <?php
                            $element->setAttribute('class', 'btn btn-primary');
                            $element->setAttribute('style', 'width:150px');

                            echo $this->formElement($element);
                            ?>
                        </div>
                    </div>
                    <?php
                    echo $this->form()->closeTag($form);
                    ?>
        </div>
    </div>
</section>