<p>
    <?php
    $url = $this->url($this->router, array(
        'action' => 'delete',
        'id' => $this->id
    ));
    ?>
<form action="<?php echo $url; ?>" method="post" >
    <div class="form-group" >
        <input type="hidden" name="redirecturl" 
               value="<?php echo $redirecturl; ?>" />
        <input type="hidden" name="id"
               value="<?php echo (int) $dbArray->getId(); ?>" /> 
        <input class="btn btn-warning" style="width:100px" type="submit" name="del" 
               value="Yes" /> 
        <input class="btn btn-primary" style="width:100px" type="submit"
               name="del" value="No" />
    </div>
</form>
</div>
</div>
</section>