<section class="list">
    <?php
    $title = $this->escapeHtml($dbArray->getName());
    $this->headTitle('SIGERI - ' . $title);
    ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>
                Threat: <?php echo $this->escapeHtml($title); ?> 
                <a href="<?php echo $this->url($this->router, 
                        array('action' => 'edit', 'id' => $dbArray->getId())); ?>">                    
                    <button class="btn btn-info" style="float: right;">
                        <?php  echo $this->translate('Edit register');?>
                
                    </button></a>
            </h3>

        </div>