<?php echo $this->partial('partial/add_top.phtml'); ?>

<?php
foreach ($form as $element) :
                        if (!(in_array($element->getAttribute('name'), array('submit', 'description', 'documents')))) {
                            ?>

                            <div class="form-group <?php
                            if ($this->formElementErrors($element))
                                echo "error"
                                ?>">
                                <label class="col-sm-2 control-label"><?php echo $element->getLabel() ?></label>
                                <div class="col-sm-10">
                                    <?php
                                    //echo $element->getAttribute('type');
                                    if ($element->getAttribute('type') != 'submit') {
                                        $element->setAttribute('class', 'form-control ' . $element->getAttribute('class'));
                                    } else {
                                        $element->setAttribute('class', 'btn btn-primary');
                                        $element->setAttribute('style', 'width:150px');
                                    };

                                    //if (!$element->hasAttribute('class'))
                                    //	$element->setAttribute('class', 'form-control');
                                    echo $this->formElement($element);
                                    if ($this->formElementErrors($element))
                                        
                                        ?>
                                    <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
                                </div>
                            </div>

                            <?php
                        }
                    endforeach;
                    ?>
                    <br>
                    <input type="text" name="discr" value="methodcvss">
                    <?php $element = $this->form->get('submit'); ?>
                    <div class="form-group" style="text-align:right;">
                        <div class="col-sm-12">
                            <?php
                            $element->setAttribute('class', 'btn btn-primary');
                            $element->setAttribute('style', 'width:150px');

                            echo $this->formElement($element);
                            ?>
                        </div>
                    </div>

                    ?> 
<?php echo $this->partial('partial/add_bottom.phtml'); ?>