<?php echo $this->partial('partial/delete_top.phtml'); ?>
<div class="panel-body">
    <p>Are you sure that you want to delete?</p>
    <label>ID:</label> <?php echo $this->escapeHtml($dbArray->getId()); ?> <br>
    <label>Method:</label> <?php echo $this->escapeHtml($dbArray->getMethod()); ?> <br>
    <label>Value:</label> <?php echo $this->escapeHtml($dbArray->getValue()); ?> <br>
    <label>Risk:</label> <?php echo $this->escapeHtml($dbArray->getRisk()); ?>

    <?php
    echo $this->partial('partial/delete_bottom.phtml');
    