<section class="list">
    <?php
    $title = $this->escapeHtml($dbArray->getId());
    $this->headTitle('SIGERI - ' . $title);
    ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3><?php echo $this->escapeHtml($title); ?></h3>
        </div>
        <div class="panel-body">
            <p>
                <a href="<?php
                echo $this->url('method'.$dbArray->getMethod(), array('action' => 'edit', 'id' => $dbArray->getId()));
                ?>">
                    Edit register</a> 
            </p>

            <p><label>ID: </label> <?php echo $this->escapeHtml($dbArray->getId()); ?></p> 
            <p><label>Method: </label> <?php echo $this->escapeHtml($dbArray->getMethod()); ?></p> 
            <p><label>Risk: </label> <?php echo $this->escapeHtml($dbArray->getRisk()); ?></p> 
            <p><label>Value: </label> <?php echo $this->escapeHtml($dbArray->getValue()); ?></p> 

        </div>
    </div>
</section>

