<?php echo $this->partial('partial/view_top.phtml'); ?>

<div class="panel-body">

    <p><label>ID: </label> <?php echo $this->escapeHtml($dbArray->getId()); ?></p> 
    <p><label>Method: </label> <?php echo $this->escapeHtml($dbArray->getMethod()); ?></p> 
    <p><label>Risk: </label> <?php echo $this->escapeHtml($dbArray->getRisk()); ?></p> 
    <p><label>Value: </label> <?php echo $this->escapeHtml($dbArray->getValue()); ?></p> 

</div>
</div>

<?php
echo $this->partial('partial/view_bottom.phtml');

