<?php echo $this->partial('partial/delete_top.phtml'); ?>
<div class="panel-body">
    <p>Are you sure that you want to delete?</p>
    <label>Plan:</label> <?php echo $this->escapeHtml($dbArray->getName()); ?> <br>
    <label>Analyst:</label> <?php echo $this->escapeHtml($dbArray->getAnalyst()); ?> <br>
    <label>Status:</label> <?php echo $this->escapeHtml($dbArray->getStatus()); ?> <br>
    <label>Registered:</label> <?php echo $this->dateFormat($dbArray->getUpdated(), IntlDateFormatter::LONG); ?> <br> 

    <?php
    echo $this->partial('partial/delete_bottom.phtml');
   