<?php echo $this->partial('partial/delete_top.phtml'); ?>
<div class="panel-body">
    <p>Are you sure that you want to delete?</p>
    <label>Name:</label> <?php echo $this->escapeHtml($dbArray->getName()); ?> <br>
    <label>Registered:</label> <?php echo$this->dateFormat($dbArray->getCreated(), IntlDateFormatter::LONG); ?><br>
    <label>Last Change:</label> <?php echo$this->dateFormat($dbArray->getUpdated(), IntlDateFormatter::LONG); ?>

    <?php
    echo $this->partial('partial/delete_bottom.phtml');

    