<<?php echo $this->partial('partial/list_top.phtml'); ?>
<table id="datatable" class="table table-striped responsive-utilities jambo_table bulk_action">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>         
            <th>Status</th>
            <th>Analyst</th>
            <th>Date</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($dbArray as $dbRow) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($dbRow->getId()); ?></td>
                <td><?php echo $this->escapeHtml($dbRow->getName()); ?></td>                    
                <td><?php echo $this->escapeHtml($dbRow->getStatus()); ?></td>                                             
                <td><?php echo $this->escapeHtml($dbRow->getAnalyst()); ?></td>                                             
                <td><?php echo $this->dateFormat($dbRow->getUpdated(), IntlDateFormatter::SHORT); ?></td>
                <td><a
                        href="<?php
                        echo $this->url($this->router, array(
                            'action' => 'view',
                            'id' => $dbRow->getId()
                        ));
                        ?>">View </a>
                    <a
                        href="<?php
                        echo $this->url($this->router, array(
                            'action' => 'edit',
                            'id' => $dbRow->getId()
                        ));
                        ?>">Edit</a>
                    <a
                        href="<?php
                        echo $this->url($this->router, array(
                            'action' => 'delete',
                            'id' => $dbRow->getId()
                        ));
                        ?>">Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php echo $this->partial('partial/list_bottom.phtml'); 