<?php echo $this->partial('partial/view_top.phtml'); ?>

<div class="panel-body">

    <p><label>ID: </label> <?php echo $this->escapeHtml($dbArray->getId()); ?></p>   
    <p><label>Status: </label> <?php echo $this->escapeHtml($dbArray->getStatus()); ?></p>
    <p><label>Type: </label> <?php echo $this->escapeHtml($dbArray->getType()); ?></p>
    <p><label>Analyst: </label> <?php echo $this->escapeHtml($dbArray->getAnalyst()); ?></p>
    <p><label>Register: </label> <?php echo $this->escapeHtml($dbArray->getFormatedDate()); ?></p>



    <ul class="nav nav-tabs nav-justified" style="color:#000;font-weight: bold;">
        <li class="active"><a data-toggle="tab" href="#description">Description</a></li>
        <li><a data-toggle="tab" href="#notes">Notes</a></li>
        <li><a data-toggle="tab" href="#documents">Documents</a></li>
        <li><a data-toggle="tab" href="#revisions">Revisions</a></li>        
    </ul>
    <div class="panel" style="padding-top:5px;">

        <div class="tab-content col-sm-12">
            <div id="description" class="tab-pane fade in active">
                <p><?php echo $dbArray->getDescription(); ?></p>
            </div>
            <div id="notes" class="tab-pane fade in">
                <p><?php echo $dbArray->getAnnotations(); ?></p>
            </div>                    
            <div id="documents" class="tab-pane fade in">
                <?php echo $this->partial('partial/list_documents.phtml'); ?>
            </div>
            <div id="revisions" class="tab-pane fade in">
                <p>
                    <a href="<?php
                    echo $this->url('controlversion', array('action' => 'add'), array('query' => array('control_id' => $dbArray->getId()))
                    );
                    ?>">
                        New revision register</a> 
                </p>
                <table id="datatable" class="table table-striped responsive-utilities jambo_table bulk_action">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Status</th>                
                            <th>Analyst</th>
                            <th>Register</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>                                
                        <?php foreach ($vsArray as $dbRow) : ?>
                            <tr>
                                <td><?php echo $this->escapeHtml($dbRow->getId()); ?></td>
                                <td><?php echo $this->escapeHtml($dbRow->getName()); ?></td>
                                <td><?php echo $this->escapeHtml($dbRow->getStatus()); ?></td>
                                <td><?php echo $this->escapeHtml($dbRow->getAnalyst()); ?></td>
                                <td><?php echo $this->escapeHtml($dbRow->getFormatedDate()); ?></td>
                                <td><a target="_blank"
                                       href="<?php
                                       echo $this->url('controlversion', array(
                                           'action' => 'view',
                                           'id' => $dbRow->getId()
                                       ));
                                       ?>">View</a>
                                    <a
                                        href="<?php
                                        echo $this->url('controlversion', array(
                                            'action' => 'edit',
                                            'id' => $dbRow->getId()
                                        ));
                                        ?>">Edit</a>
                                    <a
                                        href="<?php
                                        echo $this->url('controlversion', array(
                                            'action' => 'delete',
                                            'id' => $dbRow->getId()
                                        ));
                                        ?>">Del</a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>

        </div>
    </div>

</div>
</div>
<?php echo $this->partial('partial/view_bottom.phtml'); 