<section class="add">
    <?php
    $title = 'Add ' . $this->title;
    $this->headTitle('SIGERI - ' . $title);
    ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3><?php echo $this->escapeHtml($title); ?></h3>
        </div>
        <div class="panel-body">

            <?php if ($this->error): ?>
                <p class="error">There were one or more issues with your submission. Please correct...</p>
            <?php endif ?>

            <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url);
            $form->setAttribute('class', 'form-horizontal');
            $form->prepare();

            echo $this->form()->openTag($form);

            foreach ($form as $element) :
                ?>

                <div class="form-group <?php
                if ($this->formElementErrors($element))
                    echo "error"
                    ?>">
                    <label class="col-sm-2 control-label"><?php echo $element->getLabel() ?></label>
                    <div class="col-sm-10">
                        <?php
                        //echo $element->getAttribute('type');
                        if ($element->getAttribute('type') != 'submit') {
                            $element->setAttribute('class', 'form-control');
                        } else {
                            $element->setAttribute('class', 'btn btn-primary');
                            $element->setAttribute('style', 'width:150px');
                        };

                        //if (!$element->hasAttribute('class'))
                        //	$element->setAttribute('class', 'form-control');
                        echo $this->formElement($element);
                        if ($this->formElementErrors($element))
                            
                            ?>
                        <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
                    </div>
                </div>

                <?php
            endforeach;
            echo $this->form()->closeTag($form);
            ?>
        </div>
    </div>
</section>