<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 ' . $this->translate('Risk'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge') ?>

        <!-- Le styles -->
<?php
echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'
        ))
        ->prependStylesheet($this->basePath() . '/multiselect/css/multi-select.css')
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/datatables/css/jquery.dataTables.min.css')
        
?>

        <!-- Scripts -->
<?php
echo $this->headScript()
        ->prependFile($this->basePath() . '/multiselect/js/jquery.multi-select.js')
        ->prependFile($this->basePath() . '/datatables/js/jquery.dataTables.min.js')
        ->prependFile($this->basePath() . '/ckeditor/ckeditor.js')
        ->prependFile($this->basePath() . '/multiselect/js/jquery.quicksearch.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ))->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array(
    'conditional' => 'lt IE 9'
));
?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse"
                            data-target=".navbar-collapse">
                        <span class="icon-bar"></span> <span class="icon-bar"></span> <span
                            class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img
                            src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Risk" />&nbsp;<?php echo $this->translate('Risk') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="dropdown"><a href="#" class="dropdown-toggle"
                                                data-toggle="dropdown" role="button" aria-expanded="false">Assets
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="/asset/list">Assets</a></li>
                                <li><a href="/assettype/list">Asset Types</a></li>
                                <li class="divider"></li>
                                <li><a href="/vulnerability/list">Vulnerabilities</a></li>
                                <li><a href="/vulnerabilitytype/list">Vulnerability Type</a></li>
                                <li><a href="/vulnerabilitylevel/list">Vulnerability Level</a></li>
                                <li class="divider"></li>
                                <li><a href="/threat/list">Threat</a></li>
                                <li><a href="/threattype/list">Threat Type</a></li>
                                <li><a href="/threatlevel/list">Threat Level</a></li>
                                <li><a href="/threatsource/list">Threat Source</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Asset Reports</a></li>
                            </ul></li>
                    </ul>

                    <ul class="nav navbar-nav">
                        <li class="dropdown"><a href="#" class="dropdown-toggle"
                                                data-toggle="dropdown" role="button" aria-expanded="false">Risk <span
                                    class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="/risk/list">Risks</a></li>
                                <li><a href="/risktype/list">Risk Types</a></li>
                                <li><a href="/riskstatus/list">Risk Status</a></li>
                                <li><a href="/riskreview/list">Risk Reviews</a></li>
                                <li class="divider"></li>
                                <li><a href="/impact/list">Impact</a></li>
                                <li><a href="/probability/list">Probability</a></li>
                                <li class="divider"></li>
                                <li><a href="/control/list">Controls</a></li>                                    
                                <li><a href="/controltype/list">Control Types</a></li>
                                <li><a href="/controlstatus/list">Control Status</a></li>
                                <li><a href="/controlreview/list">Control Reviews</a></li>
                                <li class="divider"></li>
                                <li><a href="/compliance/list">Compliance</a></li>                                    
                                <li><a href="/compliancetype/list">Compliance Types</a></li>
                                <li><a href="/compliancerule/list">Compliance Rules</a></li>
                            </ul></li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li class="dropdown"><a href="#" class="dropdown-toggle"
                                                data-toggle="dropdown" role="button" aria-expanded="false">Plans
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">                                
                                <li><a href="/plan/list">Plans</a></li>
                                <li><a href="/planreview/list">Plan Reviews</a></li> 
                                <li><a href="/planstatus/list">Plan Status</a></li> 
                                <li><a href="/planstrategy/list">Plan Strategies</a></li> 
                                <li><a href="/planeffort/list">Plan Efforts</a></li> 
                                <li class="divider"></li>
                                <li><a href="#">Calendar</a></li>
                            </ul></li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li class="dropdown"><a href="#" class="dropdown-toggle"
                                                data-toggle="dropdown" role="button" aria-expanded="false">Reports
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="/risk/xychart">Risk XYChart</a></li>
                                <li><a href="/risk/barchart">Risk BarChart</a></li>
                                <li><a href="/risk/columnchart">Risk ColumnChart</a></li>
                                <li class="divider"></li>
                                <li><a href="#">---</a></li>
                            </ul></li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li class="dropdown"><a href="#" class="dropdown-toggle"
                                                data-toggle="dropdown" role="button" aria-expanded="false">Admin <span
                                    class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="/user/list">Users</a></li>
                                <li><a href="/group/list">Groups</a></li>
                                <li><a href="/unit/list">Unit</a></li>
                                <li class="divider"></li>
                                <li><a href="/document/list">Documents</a></li>
                                <li><a href="/folder/list">Folders</a></li>
                                <li class="divider"></li>
                                <li><a href="/asset/zabbix">Import from Zabbix</a></li>
                                <li><a href="/asset/ldap">Import from LDAP</a></li>
                            </ul></li>
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
<?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div>
        <!-- /container -->
<?php echo $this->inlineScript() ?>

        <script>
            var demo1 = $('select[multiple="multiple"]').multiSelect({
                keepOrder: true,
                selectableHeader: "<input type='text' class='search-input' autocomplete='off' placeholder='try \"12\"'>",
                selectionHeader: "<input type='text' class='search-input' autocomplete='off' placeholder='try \"4\"'>",
                afterInit: function (ms) {
                    var that = this,
                            $selectableSearch = that.$selectableUl.prev(),
                            $selectionSearch = that.$selectionUl.prev(),
                            selectableSearchString = '#' + that.$container.attr('id') + ' .ms-elem-selectable:not(.ms-selected)',
                            selectionSearchString = '#' + that.$container.attr('id') + ' .ms-elem-selection.ms-selected';

                    that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
                            .on('keydown', function (e) {
                                if (e.which === 40) {
                                    that.$selectableUl.focus();
                                    return false;
                                }
                            });

                    that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
                            .on('keydown', function (e) {
                                if (e.which == 40) {
                                    that.$selectionUl.focus();
                                    return false;
                                }
                            });
                },
                afterSelect: function () {
                    this.qs1.cache();
                    this.qs2.cache();
                },
                afterDeselect: function () {
                    this.qs1.cache();
                    this.qs2.cache();
                }
            });

        </script>
    </body>


</html>
