<section class="edit">
    <div class="row">
        <div class="col-md-8">
            <?php
            $title = 'Edit ' . $this->title;
            $this->headTitle('SIGERI - ' . $title);
            ?>

            <h2><?php echo $this->escapeHtml($title); ?></h2>

            <?php if ($this->error): ?>
                <p class="error">There were one or more issues with your submission. Please correct...</p>
            <?php endif ?>

            <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url);
            $form->setAttribute('class', 'form-horizontal');
            $form->prepare();

            echo $this->form()->openTag($form);
            ?>

            <div class="form-group <?php
            $element = $this->form->get('name');
            if ($this->formElementErrors($element))
                echo "error"
                ?>">
                <label class="col-sm-2 control-label"><?php echo $element->getLabel() ?></label>
                <div class="col-sm-10">
                    <?php
                    $element->setAttribute('class', 'form-control');

                    echo $this->formElement($element);
                    if ($this->formElementErrors($element))
                        
                        ?>
                    <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
                </div>
            </div>
            <div class="form-group <?php
            $element = $this->form->get('description');
            if ($this->formElementErrors($element))
                echo "error"
                ?>">
                <label class="col-sm-2 control-label"><?php echo $element->getLabel() ?></label>
                <div class="col-sm-10">
                    <?php
                    $element->setAttribute('class', 'form-control');

                    echo $this->formElement($element);
                    if ($this->formElementErrors($element))
                        
                        ?>
                    <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
                </div>
            </div>

            <div class="form-group <?php
            $element = $this->form->get('type');
            if ($this->formElementErrors($element))
                echo "error"
                ?>">
                <label class="col-sm-2 control-label"><?php echo $element->getLabel() ?></label>
                <div class="col-sm-10">
                    <?php
                    $element->setAttribute('class', 'form-control');

                    echo $this->formElement($element);
                    if ($this->formElementErrors($element))
                        
                        ?>
                    <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
                </div>
            </div>

            <div class="form-group <?php
            $element = $this->form->get('analyst');
            if ($this->formElementErrors($element))
                echo "error"
                ?>">
                <label class="col-sm-2 control-label"><?php echo $element->getLabel() ?></label>
                <div class="col-sm-10">
                    <?php
                    $element->setAttribute('class', 'form-control');

                    echo $this->formElement($element);
                    if ($this->formElementErrors($element))
                        
                        ?>
                    <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
                </div>
            </div>

            <div class="form-group <?php
            $element = $this->form->get('unit');
            if ($this->formElementErrors($element))
                echo "error"
                ?>">
                <label class="col-sm-2 control-label"><?php echo $element->getLabel() ?></label>
                <div class="col-sm-10">
                    <?php
                    $element->setAttribute('class', 'form-control');

                    echo $this->formElement($element);
                    if ($this->formElementErrors($element))
                        
                        ?>
                    <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
                </div>
            </div>

            <div class="form-group <?php
            $element = $this->form->get('location');
            if ($this->formElementErrors($element))
                echo "error"
                ?>">
                <label class="col-sm-2 control-label"><?php echo $element->getLabel() ?></label>
                <div class="col-sm-10">
                    <?php
                    $element->setAttribute('class', 'form-control');

                    echo $this->formElement($element);
                    if ($this->formElementErrors($element))
                        
                        ?>
                    <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
                </div>
            </div>
                <style>
                    ul a {
                        color:#000;
                    }
                </style>
            <ul class="nav nav-tabs nav-justified" style="color:#000;font-weight: bold;">
                <li class="active"><a data-toggle="tab" href="#risks">Risks</a></li>
                <li><a data-toggle="tab" href="#vulnerabilities">Vulnerabilities</a></li>
                <li><a data-toggle="tab" href="#threaties">Threaties</a></li>
                <li><a data-toggle="tab" href="#plans">Plans</a></li>
                <li><a data-toggle="tab" href="#dependencies">Dependencies</a></li>
                <li><a data-toggle="tab" href="#documents">Documents</a></li>
                <li><a data-toggle="tab" href="#revisions">Revisions</a></li>
            </ul>
            <div class="panel" style="padding-top:5px;">

                <div class="tab-content col-sm-12">
                    <div id="risks" class="tab-pane fade in active">
                        <div class="form-group <?php
                        $element = $this->form->get('risks');
                        if ($this->formElementErrors($element))
                            echo "error"
                            ?>">
                            <div>
                                <?php
                                $element->setAttribute('class', 'form-control');

                                echo $this->formElement($element);
                                if ($this->formElementErrors($element))
                                    
                                    ?>
                                <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
                            </div>
                        </div>
                    </div>

                    <div id="vulnerabilities" class="tab-pane fade">
                        <div class="form-group <?php
                        $element = $this->form->get('vulnerabilities');
                        if ($this->formElementErrors($element))
                            echo "error"
                            ?>">
                            <div>
                                <?php
                                $element->setAttribute('class', 'form-control');

                                echo $this->formElement($element);
                                if ($this->formElementErrors($element))
                                    
                                    ?>
                                <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
                            </div>
                        </div>
                    </div>
                    <div id="threaties" class="tab-pane fade">
                        <div class="form-group <?php
                        $element = $this->form->get('threaties');
                        if ($this->formElementErrors($element))
                            echo "error"
                            ?>">
                            <div>
                                <?php
                                $element->setAttribute('class', 'form-control');

                                echo $this->formElement($element);
                                if ($this->formElementErrors($element))
                                    
                                    ?>
                                <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
                            </div>
                        </div>
                    </div>
                    <div id="plans" class="tab-pane fade">
                        <div class="form-group <?php
                        $element = $this->form->get('plans');
                        if ($this->formElementErrors($element))
                            echo "error"
                            ?>">
                            <div>
                                <?php
                                $element->setAttribute('class', 'form-control');

                                echo $this->formElement($element);
                                if ($this->formElementErrors($element))
                                    
                                    ?>
                                <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
                            </div>
                        </div>
                    </div>
                    <div id="dependencies" class="tab-pane fade">
                        <div class="form-group <?php
                        $element = $this->form->get('dependencies');
                        if ($this->formElementErrors($element))
                            echo "error"
                            ?>">
                            <div>
                                <?php
                                $element->setAttribute('class', 'form-control');

                                echo $this->formElement($element);
                                if ($this->formElementErrors($element))
                                    
                                    ?>
                                <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
                            </div>
                        </div>
                    </div>
                    <div id="documents" class="tab-pane fade">
                        <div class="form-group <?php
                        $element = $this->form->get('documents');
                        if ($this->formElementErrors($element))
                            echo "error"
                            ?>">
                            <div>
                                <?php
                                $element->setAttribute('class', 'form-control');

                                echo $this->formElement($element);
                                if ($this->formElementErrors($element))
                                    
                                    ?>
                                <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
                            </div>
                        </div>
                    </div>
                    <div id="revisions" class="tab-pane fade">
                        Revisions
                    </div>
                </div>
                <?php $element = $this->form->get('submit'); ?>
                <div class="form-group" style="text-align:right;">
                    <div class="col-sm-12">
                        <?php
                        $element->setAttribute('class', 'btn btn-primary');
                        $element->setAttribute('style', 'width:150px');

                        echo $this->formElement($element);
                        ?>
                    </div>
                </div>       
            </div>
            <?php echo $this->form()->closeTag($form); ?>

        </div>
        <div class="col-md-4">
        </div>
    </div>
</section>