<section class="list">
<?php
		$title = 'List ' . $this->title;
		$this->headTitle ( 'SIGERI - ' . $title );
	?>
	<h2><?php echo $this->escapeHtml($title); ?></h2>
	<p>	<a
			href="<?php echo $this->url($this->router, array('action'=>'add'));?>">Add new register</a>
	</p>
<table class="table">
		 <tr>
		     <th>ID</th>
		     <th>Name</th>
		     <th>Type</th>
		     <th>Unit</th>
		     <th>Analyst</th>
		     <th>Risks</th>
		     <th>Dependencias</th>
		     <th>&nbsp;</th>
		 </tr>
		 <?php foreach ($dbArray as $dbRow ) : ?>
		 <tr>
		     <td><?php echo $this->escapeHtml($dbRow->getId());?></td>
		     <td><?php echo $this->escapeHtml($dbRow->getName());?></td>
		     <td><?php echo $this->escapeHtml($dbRow->getType());?></td>     
		     <td><?php echo $this->escapeHtml($dbRow->getUnit());?></td>
		     <td><?php echo $this->escapeHtml($dbRow->getAnalyst());?></td>
		     <td><?php foreach ($dbRow->getRisks() as $risk) { echo $this->escapeHtml($risk) . "<br>";};?></td>
		     <td><?php foreach ($dbRow->getDependencies() as $dependency) { echo $this->escapeHtml($dependency) . "<br>";};?></td>
		     <td><a
					href="<?php echo $this->url ( $this->router, array (
							'action' => 'edit',
							'id' => $dbRow->getId () 
							) );
					?>">Edit</a>
					<a href="<?php echo $this->url ( $this->router, array (
							'action' => 'delete',
							'id' => $dbRow->getId () 
					) );
					?>">Delete</a>
		     </td>
		 </tr>
		 <?php endforeach; ?>
	</table>
</section>