<section class="list">
    <?php
    $title = $this->translate('List') . ': ' . $this->title;
    $this->headTitle('SIGERI - ' . $title);
    ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3><?php echo $this->escapeHtml($title); ?>
            <!-- HTML and script to redirect to another page based on the select -->            
            <div class="form-group" style="padding-right:15px; padding-left: 15px; float: right;">
                <select id="method" class="form-control">
                    <option value="serverasset">New Server Asset</option>
                    <option value="serviceasset">New Service Asset</option>
                    <option value="processasset">New Process Asset</option>
                    <option value="locationasset">New Location Asset</option>
                </select>
            </div>     
            </h3>
        </div>
        <div class="panel-body">               
            <script type="text/javascript">
                $(document).ready(function () {
                    $('select#method').on('click', function () {
                        $(location).attr('href', '/' + $(this).val() + '/add');
                    });
                });
            </script>
            <!-- HTML and script to redirect to another page based on the select -->

<!--            <p>
    <a href="<?php echo $this->url($this->router, array('action' => 'add')); ?>">Add
        new register</a> 
</p>-->

            <table id="datatable" class="table table-striped responsive-utilities jambo_table bulk_action">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Type</th>
                        <th>Unit</th>
                        <th>Analyst</th>
                        <th>Groups</th>
                        <th>Class</th>
                        <th>&nbsp;</th>
                    </tr></thead>
                <tbody>
                    <?php foreach ($dbArray as $dbRow) : ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($dbRow->getId()); ?></td>
                            <td><?php echo $this->escapeHtml($dbRow->getName()); ?></td>
                            <td><?php echo $this->escapeHtml($dbRow->getType()); ?></td>     
                            <td><?php echo $this->escapeHtml($dbRow->getUnit()); ?></td>
                            <td><?php echo $this->escapeHtml($dbRow->getAnalyst()); ?></td>
                            <td><?php
                                foreach ($dbRow->getGroups() as $group) {
                                    echo $this->escapeHtml($group) . "<br>";
                                };
                                ?></td>
                            <td><?php echo strtoupper($this->escapeHtml($dbRow->getDescr())); ?>
                            <td><a
                                    href="<?php
                                    echo $this->url($dbRow->getDescr() . 'asset', array(
                                        'action' => 'view',
                                        'id' => $dbRow->getId()
                                    ));
                                    ?>">View</a>
                                <a
                                    href="<?php
                                    echo $this->url($dbRow->getDescr() . 'asset', array(
                                        'action' => 'edit',
                                        'id' => $dbRow->getId()
                                    ));
                                    ?>">Edit</a>
                                <a
                                    href="<?php
                                    echo $this->url($dbRow->getDescr() . 'asset', array(
                                        'action' => 'delete',
                                        'id' => $dbRow->getId()
                                    ));
                                    ?>">Del</a>                                
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
<?php echo $this->partial('partial/list_bottom.phtml'); ?>
