<section class="list">
    <?php
    $title = 'Zabbix Hosts ';
    $this->headTitle('SIGERI - ' . $title);
    ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3><?php echo $this->escapeHtml($title); ?></h3>
        </div>
        <div class="panel-body">
            <table id="datatable" class="display table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Type</th>                        
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($return as $forms) : ?>                    
                        <tr>
                    <form method='post' class='ajaxform'>
                        <td><?php echo $this->formElement($forms['form']->get('name')); ?></td>
                        <td><?php echo $this->formElement($forms['form']->get('type')); ?></td>                            
                        <td>
                            <?php
                            if ($forms['exist'] === 'true') {
                                echo "<input disabled='true' class='btn btn-primary' type='submit' value='Added'>";
                            } else {
                                echo "<input class='btn btn-primary' type='submit' value='Add...'>";
                            }
                            ?>

                        </td>
                    </form>
                    </tr>

                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</section>
<script>

    $(document).ready(function () {
        var table = $('#datatable').DataTable({
            "pageLength": 20,
        });

        $(".ajaxform").submit(function () {
            var formData = {
                'name': $('input[name=name]').val()
            };
            $.ajax({
                url: 'updateAsset',
                type: 'Post',
                //dataType: 'json',
                async: true,
                data: $(this).serialize(),
                success: function (data, status) {
                    console.log('success ');
                },
                error: function (xhr, textStatus, errorThrown) {
                    if (xhr.status === 0) {
                        alert('Not connected. Verify Network.');
                    } else if (xhr.status == 404) {
                        alert('Requested page not found. [404]');
                    } else if (xhr.status == 500) {
                        alert('Server Error [500].');
                    } else if (errorThrown === 'parsererror') {
                        alert('Requested JSON parse failed.');
                    } else if (errorThrown === 'timeout') {
                        alert('Time out error.');
                    } else if (errorThrown === 'abort') {
                        alert('Ajax request aborted.');
                    } else {
                        alert('Remote sever unavailable. Please try later');
                    }
                }
            });
            return false;
        });

    });
</script>
