            <?php $element = $this->form->get('submit'); ?>
            <div class="form-group" style="text-align:right;">
                <div class="col-sm-12">
                    <?php
                    $element->setAttribute('class', 'btn btn-primary');
                    $element->setAttribute('style', 'width:150px');
                    echo $this->formElement($element);
                    ?>
                </div>
            </div>
            <?php
            echo $this->form()->closeTag($form);
            ?>
        </div>
</section>

<script>
    $(document).ready(function () {
        var table = $('.table').DataTable({
            "lengthChange": false,
            "pagingType": "simple",
            "pageLength": 10,
            "searching": false,
            responsive: true,
        });
    });
</script>