<section class="list">
    <?php
    $title = 'List ' . $this->title;
    $this->headTitle('SIGERI - ' . $title);
    ?>

    <h2><?php echo $this->escapeHtml($title); ?></h2>
    <p>
        <a href="<?php echo $this->url($this->router, array('action' => 'add')); ?>">Add
            new register</a> 
    </p>

    <table id="datatable" class="display table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>               
                <th>Description</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($dbArray as $dbRow) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($dbRow->getId()); ?></td>
                    <td><?php echo $this->escapeHtml($dbRow->getName()); ?></td>                    
                    <td><?php echo $this->escapeHtml($dbRow->getDescription()); ?></td>
                    <td><a
                            href="<?php
                            echo $this->url($this->router, array(
                                'action' => 'edit',
                                'id' => $dbRow->getId()
                            ));
                            ?>">Edit</a>
                        <a
                            href="<?php
                            echo $this->url($this->router, array(
                                'action' => 'delete',
                                'id' => $dbRow->getId()
                            ));
                            ?>">Delete</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</section>

<script>

    $(document).ready(function () {
        var table = $('#datatable').DataTable({
            "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
            "pageLength": 50,
        });

    });
</script>