<?php echo $this->partial('partial/add_top.phtml'); ?>
<?php
foreach ($form as $element) :
    ?>

    <div class="form-group <?php
    if ($this->formElementErrors($element))
        echo "error"
        ?>">
        <label class="col-xs-2 col-sm-2 col-md-2 control-label"><?php echo $element->getLabel() ?></label>
        <div class="col-xs-10 col-sm-10 col-md-10">
            <?php
            $element->setAttribute('class', 'form-control ' . $element->getAttribute('class'));

            //if (!$element->hasAttribute('class'))
            //	$element->setAttribute('class', 'form-control');
            echo $this->formElement($element);
            if ($this->formElementErrors($element))
                
                ?>
            <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
        </div>
    </div>

    <?php
endforeach;
?>


<?php echo $this->partial('partial/add_bottom.phtml'); ?>