<section class="delete">
	<h2>Delete Asset Manager</h2>

<?php
// module/Album/view/album/album/delete.phtml:
$title = 'Delete Asset Manager';
$this->headTitle ( $title );
?>
	<p>Are you sure that you want to delete	
	<p>
    Asset Type: '<?php echo $this->escapeHtml($dbArray->getName()); ?>' <br>
    Description: '<?php echo $this->escapeHtml($dbArray->getEmail()); ?>'?
    </p>
	</p>
<?php
$url = $this->url ( 'assetmanager', array (
		'action' => 'delete',
		'id' => $this->id 
) );
?>
<form action="<?php echo $url; ?>" method="post">
		<div>
			<input type="hidden" name="id"
				value="<?php echo (int) $dbArray->getId(); ?>" /> <input
				type="submit" name="del" value="Yes" /> <input type="submit"
				name="del" value="No" />
		</div>
	</form>
</section>