<?php

 $title = 'Asset Manager List';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('assetmanager', array('action'=>'add'));?>">Add new asset manager</a>
 </p> 
 <table class="table">
 <tr>
     <th>ID</th>
     <th>Name</th>
     <th>Email</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($dbArray as $dbRow ) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($dbRow->getId());?></td>
     <td><?php echo $this->escapeHtml($dbRow->getName());?></td>
     <td><?php echo $this->escapeHtml($dbRow->getEmail());?></td>
     <td>
         <a href="<?php echo $this->url('assetmanager',
             array('action'=>'edit', 'id' => $dbRow->getId()));?>">Edit</a>
         <a href="<?php echo $this->url('assetmanager',
             array('action'=>'delete', 'id' => $dbRow->getId()));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
