<section class="list"><?php
$title = 'Asset Type List';
$this->headTitle ( $title );
?>
 <h2><?php echo $this->escapeHtml($title); ?></h2>
	<p>
		<a
			href="<?php echo $this->url('assettype', array('action'=>'add'));?>">Add
			new asset type</a>
	</p>
	<table class="table">
		<tr>
			<th>ID</th>
			<th>Name</th>
			<th>Description</th>
			<th>&nbsp;</th>
		</tr>
 <?php foreach ($dbArray as $dbRow ) : ?>
 <tr>
			<td><?php echo $this->escapeHtml($dbRow->getId());?></td>
			<td><?php echo $this->escapeHtml($dbRow->getName());?></td>
			<td><?php echo $this->escapeHtml($dbRow->getDescription());?></td>
			<td><a
				href="<?php
		
echo $this->url ( 'assettype', array (
				'action' => 'edit',
				'id' => $dbRow->getId () 
		) );
		?>">Edit</a>
				<a
				href="<?php
		
echo $this->url ( 'assettype', array (
				'action' => 'delete',
				'id' => $dbRow->getId () 
		) );
		?>">Delete</a>
			</td>
		</tr>
 <?php endforeach; ?>
 </table>
</section>