<section class="list">
    <?php
    $title = $this->escapeHtml($dbArray->getName());
    $this->headTitle('SIGERI - ' . $title);
    ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3><?php echo $this->escapeHtml($title); ?></h3>
        </div>
        <div class="panel-body">
            <p><a href="<?php echo $this->url($this->router, array('action' => 'edit', 'id' => $dbArray->getId())); ?>">
                    Edit register</a> 
            </p>

            <p><label>ID: </label> <?php echo $this->escapeHtml($dbArray->getId()); ?></p>   
            <p><label>Status: </label> <?php echo $this->escapeHtml($dbArray->getStatus()); ?></p>
            <p><label>Type: </label> <?php echo $this->escapeHtml($dbArray->getType()); ?></p>
            <p><label>Analyst: </label> <?php echo $this->escapeHtml($dbArray->getAnalyst()); ?></p>
            <p><label>Register: </label> <?php echo $this->escapeHtml($dbArray->getFormatedDate()); ?></p>



            <ul class="nav nav-tabs nav-justified" style="color:#000;font-weight: bold;">
                <li class="active"><a data-toggle="tab" href="#description">Description</a></li>
                <li><a data-toggle="tab" href="#notes">Notes</a></li>
                <li><a data-toggle="tab" href="#documents">Documents</a></li>    
            </ul>
            <div class="panel" style="padding-top:5px;">

                <div class="tab-content col-sm-12">
                    <div id="description" class="tab-pane fade in active">
                        <p><?php echo $dbArray->getDescription(); ?></p>
                    </div>
                    <div id="notes" class="tab-pane fade in">
                        <p><?php echo $dbArray->getAnnotations(); ?></p>
                    </div>                    
                    <div id="documents" class="tab-pane fade in">
                        <?php echo $this->partial('partial/list_documents.phtml'); ?>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>


<script>

    $(document).ready(function () {
        var table = $('.table').DataTable({
            "lengthChange": false,
            "pagingType": "simple",
            "pageLength": 10,
            "searching": false
        });

    });
</script>