
<section class="delete">

    <?php
    $title = 'Delete ' . $this->title;
    $this->headTitle('SIGERI - ' . $title);
    ?>
    <h2><?php echo $this->escapeHtml($title); ?></h2>
    <p>Are you sure that you want to delete?</p>
    Name: '<?php echo $this->escapeHtml($dbArray->getName()); ?>' <br>
    Analyst: '<?php echo $this->escapeHtml($dbArray->getAnalyst()); ?>' <br>
    Registered: '<?php echo $this->escapeHtml($dbArray->getFormatedDate()); ?>' <br>
    Description: '<?php echo $this->escapeHtml($dbArray->getDescription()); ?>'
    </p>
    </p>
    <?php
    $url = $this->url($this->router, array(
        'action' => 'delete',
        'id' => $this->id
            ));
    ?>
    <form action="<?php echo $url; ?>" method="post" >
        <div class="form-group" >
            <input  type="hidden" name="id"
                    value="<?php echo (int) $dbArray->getId(); ?>" /> 
            <input class="btn btn-warning" style="width:100px" type="submit" name="del" 
                   value="Yes" /> 
            <input class="btn btn-primary" style="width:100px" type="submit"
                   name="del" value="No" />
        </div>
    </form>
</section>