<section class="list">
    <?php
    $title = 'Plan: ' . $this->escapeHtml($dbArray->getName());
    $this->headTitle('SIGERI - ' . $title);
    ?>

    <h3><?php echo $this->escapeHtml($title); ?></h3>    

    <p><label>ID: </label> <?php echo $this->escapeHtml($dbArray->getId()); ?></p>   
    <p><label>Status: </label> <?php echo $this->escapeHtml($dbArray->getStatus()); ?></p>                
    <p><label>Analyst: </label> <?php echo $this->escapeHtml($dbArray->getAnalyst()); ?></p>
    <p><label>Register: </label> <?php echo $this->escapeHtml($dbArray->getFormatedDate()); ?></p>



    <ul class="nav nav-tabs nav-justified" style="color:#000;font-weight: bold;">
        <li class="active"><a data-toggle="tab" href="#description">Description</a></li>        
        <li><a data-toggle="tab" href="#revisions">Revisions</a></li>        
    </ul>
    <div class="panel" style="padding-top:5px;">

        <div class="tab-content col-sm-12">
            <div id="description" class="tab-pane fade in active">
                <p><?php echo $this->escapeHtml($dbArray->getDescription()); ?></p>
            </div>
            
            <div id="revisions" class="tab-pane fade in">
                <p>
                    <a href="<?php echo $this->url('planreview', array('action' => 'add')); ?>">
                        New revision register</a> 
                </p>
                <table id="datatable" class="display table">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Status</th>                
                            <th>Analyst</th>
                            <th>Register</th>
                            <th>Description</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($dbArray->getPlans() as $dbRow) : ?>
                            <tr>
                                <td><?php echo $this->escapeHtml($dbRow->getId()); ?></td>
                                <td><?php echo $this->escapeHtml($dbRow->getName()); ?></td>
                                <td><?php echo $this->escapeHtml($dbRow->getStatus()); ?></td>
                                <td><?php echo $this->escapeHtml($dbRow->getAnalyst()); ?></td>
                                <td><?php echo $this->escapeHtml($dbRow->getFormatedDate()); ?></td>
                                <td><?php echo $this->escapeHtml($dbRow->getDescription()); ?></td>
                                <td><a
                                        href="<?php
                                        echo $this->url('planreview', array(
                                            'action' => 'edit',
                                            'id' => $dbRow->getId()
                                        ));
                                        ?>">Edit</a>
                                    <a
                                        href="<?php
                                        echo $this->url('planreview', array(
                                            'action' => 'delete',
                                            'id' => $dbRow->getId()
                                        ));
                                        ?>">Del</a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>

        </div>
    </div>


</section>

<script>

    $(document).ready(function () {
        var table = $('#datatable').DataTable({
            "lengthChange": false,
            "pagingType": "simple",
            "pageLength": 10,
            "searching": false
        });

    });
</script>