<section class="list">
<?php
		$title = 'List ' . $this->title;
		$this->headTitle ( 'SIGERI - ' . $title );
	?>
	<h2><?php echo $this->escapeHtml($title); ?></h2>
	<p>	<a
			href="<?php echo $this->url($this->router, array('action'=>'add'));?>">Add new register</a>
	</p>
<table class="table">
		 <tr>
		     <th>ID</th>
		     <td>Name</td>
		     <th>Decription</th>
		     <th>Type</th>
		     <th>Folder</th>
		     <th>&nbsp;</th>
		 </tr>
		 <?php foreach ($dbArray as $dbRow ) : ?>
		 <tr>
		     <td><?php echo $this->escapeHtml($dbRow->getId());?></td>
		     <td><?php echo $this->escapeHtml($dbRow->getName());?></td>
		     <td><?php echo $this->escapeHtml($dbRow->getDescription());?></td>     
		     <td><?php echo $this->escapeHtml($dbRow->getType());?></td>
		     <td><?php echo $this->escapeHtml($dbRow->getFolder());?></td>
		     <td><a 
		     		href="<?php echo $dbRow->getWebPath() . $dbRow->getName(); 
		     		?>">View</a>		     		
		     		<a
					href="<?php echo $this->url ( $this->router, array (
							'action' => 'edit',
							'id' => $dbRow->getId () 
							) );
					?>">Edit</a>
					<a href="<?php echo $this->url ( $this->router, array (
							'action' => 'delete',
							'id' => $dbRow->getId () 
					) );
					?>">Delete</a>
		     </td>
		 </tr>
		 <?php endforeach; ?>
	</table>
</section>