<?php echo $this->partial('partial/list_top.phtml'); ?>
<table id="datatable" class="table table-striped responsive-utilities jambo_table bulk_action">
    <thead>
        <tr>		 	
            <th>ID</th>
            <td>Name</td>
            <th>Decription</th>
            <th>Type</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($dbArray as $dbRow) : ?>
            <tr>		 	 
                <td><?php echo $this->escapeHtml($dbRow->getId()); ?></td>
                <td><?php echo $this->escapeHtml($dbRow->getName()); ?></td>
                <td><?php echo $this->escapeHtml($dbRow->getDescription()); ?></td>     
                <td><?php echo $this->escapeHtml($dbRow->getType()); ?></td>
                <td><a target="_blank"
                        href="<?php echo $dbRow->getWebPath() . $dbRow->getName();
            ?>">View</a>		     		
                    <a
                        href="<?php
                        echo $this->url($this->router, array(
                            'action' => 'edit',
                            'id' => $dbRow->getId()
                        ));
                        ?>">Edit</a>
                    <a href="<?php
                    echo $this->url($this->router, array(
                        'action' => 'delete',
                        'id' => $dbRow->getId()
                    ));
                    ?>">Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
</section>
<?php echo $this->partial('partial/list_bottom.phtml'); ?>