<section class="list">
<?php
$title = 'Probability List';
$this->headTitle ( $title );
?>
 
 <h2><?php echo $this->escapeHtml($title); ?></h2>
	<p>
		<a href="<?php echo $this->url('probability', array('action'=>'add'));?>">Add
			new register</a>
	</p>
	<table class="table">
		<tr>
			<th>ID</th>
			<th>Value</th>
			<th>Description</th>
			<th>&nbsp;</th>
		</tr>
 <?php foreach ($dbArray as $dbRow ) : ?>
 <tr>
			<td><?php echo $this->escapeHtml($dbRow->getId());?></td>
			<td><?php echo $this->escapeHtml($dbRow->getValue());?></td>
			<td><?php echo $this->escapeHtml($dbRow->getDescription());?></td>
			<td><a
				href="<?php 
				echo $this->url ( 'probability', array (
				'action' => 'edit',
				'id' => $dbRow->getId () 
		) );
		?>">Edit</a>
				<a
				href="<?php 
				echo $this->url ( 'probability', array (
				'action' => 'delete',
				'id' => $dbRow->getId () 
		) );
		?>">Delete</a>
			</td>
		</tr>
 <?php endforeach; ?>
 </table>
</section>