<?php echo $this->partial('partial/list_top.phtml'); ?>
<table class="table">
    <tr>
        <th>ID</th>
        <th>Value</th>
        <th>Description</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($dbArray as $dbRow) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($dbRow->getId()); ?></td>
            <td><?php echo $this->escapeHtml($dbRow->getValue()); ?></td>
            <td><?php echo $this->escapeHtml($dbRow->getDescription()); ?></td>
            <td><a
                    href="<?php
                    echo $this->url($this->router, array(
                        'action' => 'edit',
                        'id' => $dbRow->getId()
                    ));
                    ?>">Edit</a>
                <a
                    href="<?php
                    echo $this->url($this->router, array(
                        'action' => 'delete',
                        'id' => $dbRow->getId()
                    ));
                    ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<?php echo $this->partial('partial/list_bottom.phtml'); ?>