<?php echo $this->partial('partial/edit_top.phtml'); ?>
<?php echo $this->partial('partial/form_asset.phtml'); ?>
<div class="panel panel-default">
    <div class="panel-heading">
        <label>Process Informations</label>
    </div>
    <div class="panel-body" style="padding: 0px">
        <ul class = "nav nav-tabs nav-justified" style = "color:#000;font-weight: bold;">
            <li class = "active"><a data-toggle = "tab" href = "#parent">Parent</a></li>                        
            <li><a data-toggle = "tab" href = "#previous">Previous</a></li>
            <li><a data-toggle = "tab" href = "#next">Next</a></li>
        </ul>
        <div class = "panel" style = "padding-top:5px;">
            <div class = "tab-content ">
                <div id = "parent" class = "tab-pane fade in">
                    <?php
                    echo $this->formElement($form->get('parent')->setAttribute('class', 'form-control ' . $form->get('parent')->getAttribute('class'))
                    );
                    ?>
                </div>                            
                <div id = "previous" class = "tab-pane fade in">
                    <?php echo $this->formElement($form->get('previous'));
                    ?>
                </div>
                <div id = "next" class = "tab-pane fade in">
                    <?php echo $this->formElement($form->get('next'));
                    ?>
                </div>                
            </div>
        </div>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <label>Process Risk Informations</label>
    </div>
    <?php echo $this->partial('partial/formtab_asset.phtml'); ?>
</div>
<?php echo $this->partial('partial/edit_bottom.phtml'); ?>