<?php echo $this->partial('partial/list_top.phtml'); ?>
<table id="datatable" class="table table-striped responsive-utilities jambo_table bulk_action">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>                        
                        <th>Risks</th>
                        <th>Dependencias</th>
                        <th>&nbsp;</th>
                    </tr></thead>
                <tbody>
                    <?php foreach ($dbArray as $dbRow) : ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($dbRow->getId()); ?></td>
                            <td><?php echo $this->escapeHtml($dbRow->getName()); ?></td>
                            <td><?php
                                foreach ($dbRow->getRisks() as $risk) {
                                    echo $this->escapeHtml($risk) . "<br>";
                                };
                                ?></td>
                            <td><?php
                                foreach ($dbRow->getDependencies() as $dependency) {
                                    echo $this->escapeHtml($dependency) . "<br>";
                                };
                                ?></td>
                            <td><a
                                    href="<?php
                                    echo $this->url($this->router, array(
                                        'action' => 'view',
                                        'id' => $dbRow->getId()
                                    ));
                                    ?>">View</a>
                                <a
                                    href="<?php
                                    echo $this->url($this->router, array(
                                        'action' => 'edit',
                                        'id' => $dbRow->getId()
                                    ));
                                    ?>">Edit</a>
                                <a href="<?php
                                echo $this->url($this->router, array(
                                    'action' => 'delete',
                                    'id' => $dbRow->getId()
                                ));
                                ?>">Delete</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
<?php echo $this->partial('partial/list_bottom.phtml'); ?>