<!DOCTYPE html>
<html lang="en">

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>SIGERI </title>

        <!-- Bootstrap core CSS -->
        <?php
        echo $this->headLink()
                // css to the dashboard...      
                ->prependStylesheet($this->basePath() . '/dash/css/custom.css')
                ->prependStylesheet($this->basePath() . '/datatables/css/jquery.dataTables.min.css')
                ->prependStylesheet($this->basePath() . '/dash/fonts/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/dash/css/animate.min.css')
                ->prependStylesheet($this->basePath() . '/dash/css/maps/jquery-jvectormap-2.0.1.css')
                ->prependStylesheet($this->basePath() . '/dash/css/icheck/flat/green.css')
                ->prependStylesheet($this->basePath() . '/dash/css/floatexamples.css')
                ->prependStylesheet($this->basePath() . '/multiselect/css/multi-select.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/d3.js')
                ->prependFile($this->basePath() . '/dash/js/custom.js')
                ->prependFile($this->basePath() . '/datatables/js/jquery.dataTables.min.js')
                ->prependFile($this->basePath() . '/dash/js/nicescroll/jquery.nicescroll.min.js')
                ->prependFile($this->basePath() . '/dash/js/nprogress.js')
                ->prependFile($this->basePath() . '/dash/js/skycons/skycons.js')
                ->prependFile($this->basePath() . '/ckeditor/ckeditor.js')
                ->prependFile($this->basePath() . '/multiselect/js/jquery.multi-select.js')
                ->prependFile($this->basePath() . '/multiselect/js/jquery.quicksearch.js')
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array(
                    'conditional' => 'lt IE 9'
                ))->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array(
            'conditional' => 'lt IE 9'));
        ?>  
    </head>
    <body class="nav-md">

        <div class="">
            <a class="hiddenanchor" id="toregister"></a>
            <a class="hiddenanchor" id="tologin"></a>

            <div id="wrapper">
                <div id="login" class="animate form">
                    <section class="login_content">
                        <form method="post" action="<?=$this->url('authentication', array('action'=>'login'));?>">
                            <h1>Login Form</h1>
                            <div>
                                <input type="text" name="username" class="form-control" placeholder="Username" required="" />
                            </div>
                            <div>
                                <input type="password" name="password" class="form-control" placeholder="Password" required="" />
                            </div>
                            <div>
                                <input type="submit" class="btn btn-default submit" value="Login" />
                                <a class="reset_pass" href="#">Lost your password?</a>
                            </div>
                            <div class="clearfix"></div>
                            <div class="separator">

                                <p class="change_link">New to site?
                                    <a href="" class="to_register"> Create Account </a>
                                </p>
                                <div class="clearfix"></div>
                                <br />
                                <div>
                                    <h1><i class="fa fa-paw" style="font-size: 26px;"></i> SIGERI</h1>

                                    <p>©2015 All Rights Reserved. SIGERI . Privacy and Terms</p>
                                </div>
                            </div>
                        </form>
                        <!-- form -->
                    </section>
                    <!-- content -->
                </div>

            </div>
        </div>
    </body>
</html>