<script type="text/javascript" src="/js/mygraph.js"></script>
<link type="text/css" href="/css/mygraph.css" rel="stylesheet">

<div class="row top_tiles">
    <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <a href="/risk/list" class="dashlink">
            <div class="tile-stats">
                <div class="icon"><i class="fa fa-exclamation-triangle"></i>
                </div>
                <div id="riskcount" class="count">
                    <script>
                        $.getJSON(
                                "/risk/count",
                                function (jsonData) {
                                    $("#riskcount").text(jsonData.rowCount);
                                }
                        );</script>
                </div>
                <h3>Risks</h3>
                <p>Registered Risks.</p>
            </div>
        </a>
    </div>
    <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <a href="/asset/list" class="dashlink">
            <div class="tile-stats">
                <div class="icon"><i class="fa fa-building"></i>
                </div>
                <div id="assetcount" class="count">
                    <script>
                        $.getJSON(
                                "/asset/count",
                                function (jsonData) {
                                    $("#assetcount").text(jsonData.rowCount);
                                }
                        );</script>
                </div>

                <h3>Assets</h3>
                <p>Registered Matriz Assets.</p>
            </div>
        </a>
    </div>
    <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <a href="/control/list" class="dashlink">
            <div class="tile-stats">
                <div class="icon"><i class="fa fa-check-square-o"></i>
                </div>
                <div id="controlcount" class="count">
                    <script>
                        $.getJSON(
                                "/control/count",
                                function (jsonData) {
                                    $("#controlcount").text(jsonData.rowCount);
                                }
                        );</script>
                </div>

                <h3>Controls</h3>
                <p>Applied Controls.</p>
            </div>
        </a>
    </div>
    <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <a href="/plan/list" class="dashlink">
            <div class="tile-stats">
                <div class="icon"><i class="fa fa-file-text"></i>
                </div>
                <div id="plancount" class="count">
                    <script>
                        $.getJSON(
                                "/plan/count",
                                function (jsonData) {
                                    $("#plancount").text(jsonData.rowCount);
                                }
                        );</script>
                </div>

                <h3>Plans</h3>
                <p>Control Risk Plans.</p>
            </div>
        </a>
    </div>
</div>



<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Risk Map <small> Global </small></h2>

                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="col-md-9 col-sm-12 col-xs-12">
                    <div class="demo-container" style="height:300px">
                        <div id="xychart01" class="xychart">
                            <script type="text/javascript">
                                // xychartChart(destiny div, json link, external links, labels, yLabel) 
                                xychart("xychart01", "/risk/jsonRiskData", ["impact", "likelihood"], "/risk/view/", 1);
                            </script>
                        </div>
                    </div>
                    <div class="tiles">
                        <div class="col-md-3 tile col-sm-3 col-xs-6">
                            <span>High Risks</span>
                            <h2 id="highrisk">
                                <script>
                                    $.getJSON(
                                            "/risk/riskcount?where=risk>15",
                                            function (jsonData) {
                                                $("#highrisk").text(jsonData.count_risk);
                                            }
                                    );</script> 
                            </h2>

                        </div>
                        <div class="col-md-3 tile col-sm-3 col-xs-6">
                            <span>Low Risks</span>
                            <h2 id="lowrisk">
                                <script>
                                    $.getJSON(
                                            "/risk/riskcount?where=risk<5",
                                            function (jsonData) {
                                                $("#lowrisk").text(jsonData.count_risk);
                                            }
                                    );</script>
                            </h2>

                        </div>
                        <div class="col-md-3 tile col-sm-3 col-xs-6">
                            <span>Assets (risk>15)</span>
                            <h2 id="assethighrisk">
                                <script>
                                    $.getJSON(
                                            "/risk/assetcount?where=risk>15",
                                            function (jsonData) {
                                                $("#assethighrisk").text(jsonData[0].assetcount);
                                            }
                                    );</script> 
                            </h2>

                        </div>
                        <div class="col-md-3 tile col-sm-3 col-xs-6">
                            <span>Assets (risk<5)</span>
                            <h2 id="assetlowrisk">
                                <script>
                                    $.getJSON(
                                            "/risk/assetcount?where=risk<5",
                                            function (jsonData) {
                                                $("#assetlowrisk").text(jsonData[0].assetcount);
                                            }
                                    );</script> 
                            </h2>

                        </div>
                    </div>

                </div>

                <div class="col-md-3 col-sm-12 col-xs-12">
                    <div>
                        <div class="x_title">
                            <h2>Top 5 Risks</h2>                            
                            <div class="clearfix"></div>
                        </div>
                        <ul class="list-unstyled top_profiles scroll-view" id="toprisk">
                            <script>
                                var composer1 = "<li class=\"media event\">\n\
                                                    <a class=\"pull-left border-aero profile_thumb\">\n\
                                                        <i class=\"fa fa-exclamation-triangle\"></i>\n\
                                                    </a><div class=\"media-body\">";

                                var composer2 = "</small></p></div></li>";
                                $.getJSON(
                                        "/risk/jsonRiskData?orderby=value&limit=5", function (result) {
                                            $.each(result, function (i, field) {
                                                $("#toprisk").append(composer1 +
                                                        "<a class=\"title\" href=\"/risk/view/" +
                                                        field.id + "\">" +
                                                        field.name + "</a><p><strong>" +
                                                        "Risk: " + field.risk + "</strong></p><p><small>" +
                                                        "likelihood: " + field.likelihood +
                                                        " | impact: " + field.impact +
                                                        composer2);
                                            });
                                        });
                            </script>                            
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<!-- Bar Graphs -->
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Risk Summary <small>Types and Groups</small></h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <div class="row" style="border-bottom: 1px solid #E0E0E0; padding-bottom: 5px; margin-bottom: 5px;">
                    <div class="col-md-6 col-sm-12 col-xs-12" style="overflow:hidden;">
                        <div id="columnchart01" >          
                            <style>
                                .column {
                                    fill: steelblue;
                                    stroke: 4px #CCC;
                                }

                                .column:hover {
                                    fill: brown;
                                }
                            </style>

                            <script type="text/javascript">
                                // columnChart(destiny div, json link, external links, labels, yLabel) 
                                columnchart("columnchart01", "/risk/jsonRiskData", "/risk/view/", 0, "likelihood x impact");
                            </script>
                        </div>
                    </div>

                    <div class="col-md-6 col-sm-12 col-xs-12">
                        <div class="row" style="text-align: center;">
                            <div class="animated flipInY col-md-4 col-sm-4 col-xs-12 ">
                                <a href="/vulnerability/list" class="dashlink">
                                    <div class="tile-stats">
                                        
                                        <div id="vulnerabilitycount" class="count">
                                            <script>
                                                $.getJSON(
                                                        "/risk/countregister?entity=vulnerability",
                                                        function (jsonData) {
                                                            $("#vulnerabilitycount").text(jsonData[0].rowCount);
                                                        }
                                                );</script>
                                        </div>
                                        <h3>Vulnerabilities</h3>
                                        <p>Vulnerabilities.</p>
                                    </div>
                                </a>
                            </div>
                            <div class="animated flipInY col-md-4 col-sm-4 col-xs-12">
                                <a href="/threat/list" class="dashlink">
                                    <div class="tile-stats">
                                        
                                        <div id="threatcount" class="count">
                                            <script>
                                                $.getJSON(
                                                        "/risk/countregister?entity=threat",
                                                        function (jsonData) {
                                                            $("#threatcount").text(jsonData[0].rowCount);
                                                        }
                                                );</script>
                                        </div>
                                        <h3>Threaties</h3>
                                        <p>Threaties.</p>
                                    </div>
                                </a>
                            </div>
                            <div class="animated flipInY col-md-4 col-sm-4 col-xs-12">
                                <a href="/risktype/list" class="dashlink">
                                    <div class="tile-stats">
                                        
                                        <div id="risktypecount" class="count">
                                            <script>
                                                $.getJSON(
                                                        "/risk/countregister?entity=risktype",
                                                        function (jsonData) {
                                                            $("#risktypecount").text(jsonData[0].rowCount);
                                                        }
                                                );</script>
                                        </div>
                                        <h3>Risk Type</h3>
                                        <p>Risk Types.</p>
                                    </div>
                                </a>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">

    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Risks and Assets <small>types</small></h2>
                <!--                <ul class="nav navbar-right panel_toolbox">
                                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                    </li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a href="#">Settings 1</a>
                                            </li>
                                            <li><a href="#">Settings 2</a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li><a class="close-link"><i class="fa fa-close"></i></a>
                                    </li>
                                </ul>-->
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="dashboard-widget-content">
                    <div class="col-md-6 col-sm-12 col-xs-12">                        
                        <div id="piechart02" class="piechart">
                            <script>
                                piechart("piechart02", "/risk/typeassetlist", 1, "Asset Type");
                            </script>

                        </div>
                        <h2 class="line_30">Asset type average risk</h2>
                        <table class="countries_list">
                            <thead style="font-weight: 800;">
                                <tr>
                                    <td>Asset type</td>
                                    <td>Number</td>
                                    <td>Avg Risk</td>
                                    <td>Max Risk</td>
                                </tr>
                            </thead>
                            <tbody id="assettable">
                            <script>
                                $.getJSON(
                                        "/risk/typeassetlist", function (result) {
                                            $.each(result, function (i, field) {
                                                $("#assettable").append(
                                                        "<tr><td>" + field.name + "</td>" +
                                                        "<td>" + field.value + "</td>" +
                                                        "<td>" + field.avgrisk + "</td>" +
                                                        "<td>" + field.maxrisk + "</td></tr>"
                                                        );
                                            });
                                        });
                            </script>                               
                            </tbody>
                        </table>
                    </div>
                    <div class="col-md-6 col-sm-12 col-xs-12">
                        <div id="piechart01" class="piechart">

                            <script>
                                piechart("piechart01", "/risk/typerisklist", 0, "Risk Type");
                            </script>

                        </div>
                        <h2 class="line_30">Risk type Average</h2>
                        <table class="countries_list">
                            <thead style="font-weight: 800;">
                                <tr>
                                    <td>Risk Type</td>
                                    <td>Number</td>
                                    <td>Avg Risk</td>
                                    <td>Max Risk</td>
                                </tr>
                            </thead>
                            <tbody id="risktable">
                            <script>
                                $.getJSON(
                                        "/risk/typerisklist", function (result) {
                                            $.each(result, function (i, field) {
                                                $("#risktable").append(
                                                        "<tr><td>" + field.name + "</td>" +
                                                        "<td>" + field.value + "</td>" +
                                                        "<td>" + field.avgrisk + "</td>" +
                                                        "<td>" + field.maxrisk + "</td></tr>"
                                                        );
                                            });
                                        });
                            </script>                               
                            </tbody>
                        </table>
                    </div>
                    <!--<div id="world-map-gdp" class="col-md-8 col-sm-12 col-xs-12" style="height:230px;"></div>-->
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="dash/js/maps/jquery-jvectormap-2.0.1.min.js"></script>
<script type="text/javascript" src="dash/js/maps/gdp-data.js"></script>
<script type="text/javascript" src="dash/js/maps/jquery-jvectormap-world-mill-en.js"></script>
<script type="text/javascript" src="dash/js/maps/jquery-jvectormap-us-aea-en.js"></script>


    <!--<script>
                                    $(function () {
                                        $('#world-map-gdp').vectorMap({
                                            map: 'world_mill_en',
                                            backgroundColor: 'transparent',
                                            zoomOnScroll: false,
                                            series: {
                                                regions: [{
                                                        values: gdpData,
                                                        scale: ['#E6F2F0', '#149B7E'],
                                                        normalizeFunction: 'polynomial'
                                                    }]
                                            },
                                            onRegionTipShow: function (e, el, code) {
                                                el.html(el.html() + ' (GDP - ' + gdpData[code] + ')');
                                            }
                                        });
                                    });
    </script>-->