<?php echo $this->partial('partial/edit_top.phtml'); ?>

        <?php
            foreach ($form as $element) :
                if ((in_array($element->getAttribute('name'), array('name', 'level', 'type', 'analyst')))) {
                    ?>

                    <div class="form-group <?php
                    if ($this->formElementErrors($element))
                        echo "error"
                        ?>">
                        <label class="col-xs-2 col-sm-2 col-md-2 control-label"><?php echo $element->getLabel() ?></label>
                        <div class="col-xs-10 col-sm-10 col-md-10">
                            <?php
                            $element->setAttribute('class', 'form-control ' . $element->getAttribute('class'));

                            //if (!$element->hasAttribute('class'))
                            //	$element->setAttribute('class', 'form-control');
                            echo $this->formElement($element);
                            if ($this->formElementErrors($element))
                                
                                ?>
                            <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
                        </div>
                    </div>

                    <?php
                }
            endforeach;
            ?> 
            <div class="form-group" >
                <span class="col-xs-2 col-sm-2 col-md-2 control-label"><b>Origin:</b></span>
                <div class="col-xs-10 col-sm-10 col-md-10">
                    <div class="form-group ">
                        <?php
                        foreach ($form as $element) :
                            if ((in_array($element->getAttribute('name'), array('deliberate', 'accidental', 'environmental')))) {
                                ?>
                                <label class="col-md-2 control-label"><?php echo $element->getLabel() ?></label>
                                <div class="col-md-1">
                                    <?php
                                    $element->setAttribute('class', 'controls ' . $element->getAttribute('class'));
                                    $element->setAttribute('style', 'margin: 12px 0px 0px');
                                    echo $this->formElement($element);
                                    if ($this->formElementErrors($element))
                                        
                                        ?>
                                    <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
                                </div>
                                <?php
                            }
                        endforeach;
                        ?> 
                    </div>
                </div>            
            </div>                
            <br>
            <ul class = "nav nav-tabs nav-justified" style = "color:#000;font-weight: bold;">
                <li class = "active"><a data-toggle = "tab" href = "#description">Description</a></li>
                <li><a data-toggle = "tab" href = "#notes">Notes</a></li>      
                <li><a data-toggle = "tab" href = "#sources">Sources</a></li>
                <li><a data-toggle = "tab" href = "#documents">Documents</a></li>
            </ul>
            <div class = "panel" style = "padding-top:5px;">
                <div class = "tab-content ">
                    <div id = "description" class = "tab-pane fade in active">
                        <?php echo $this->formElement($form->get('description'));
                        ?>
                    </div>
                    <div id = "notes" class = "tab-pane fade in">
                        <?php echo $this->formElement($form->get('annotations'));
                        ?>
                    </div>
                    <div id = "sources" class = "tab-pane fade in">
                        <?php echo $this->formElement($form->get('sources'));
                        ?>
                    </div>
                    <div id = "documents" class = "tab-pane fade in">
                        <?php echo $this->formElement($form->get('documents'));
                        ?>
                    </div>                           
                </div>
            </div>
<?php echo $this->partial('partial/edit_bottom.phtml'); ?>