<section class="list">
<?php
$title = 'Threat  List';
$this->headTitle ( $title );
?>
 
 <h2><?php echo $this->escapeHtml($title); ?></h2>
	<p>
		<a href="<?php echo $this->url('threat', array('action'=>'add'));?>">Add
			new </a>
	</p>
	<table class="table">
		<tr>
			<th>ID</th>
			<th>Name</th>
			<th>Level</th>
			<th>Type</th>
			<th>Source</th>
			<th>Analyst</th>
			<th>Date</th>
			<th>Description</th>
			<th>&nbsp;</th>
		</tr>
 <?php foreach ($dbArray as $dbRow ) : ?>
 <tr>
			<td><?php echo $this->escapeHtml($dbRow->getId());?></td>
			<td><?php echo $this->escapeHtml($dbRow->getName());?></td>
			<td><?php echo $this->escapeHtml($dbRow->getLevel());?></td>
			<td><?php echo $this->escapeHtml($dbRow->getType());?></td>
			<td><?php echo $this->escapeHtml($dbRow->getSource());?></td>
			<td><?php echo $this->escapeHtml($dbRow->getAnalyst());?></td>
			<td><?php echo $this->escapeHtml($dbRow->getFormatedDate());?></td>
			<td><?php echo $this->escapeHtml($dbRow->getDescription());?></td>
			<td><a
				href="<?php 
				echo $this->url ( 'threat', array (
				'action' => 'edit',
				'id' => $dbRow->getId () 
		) );
		?>">Edit</a>
				<a
				href="<?php 
				echo $this->url ( 'threat', array (
				'action' => 'delete',
				'id' => $dbRow->getId () 
		) );
		?>">Delete</a>
			</td>
		</tr>
 <?php endforeach; ?>
 </table>
</section>