<?php echo $this->partial('partial/list_top.phtml'); ?>

<table id="datatable" class="display table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Level</th>
            <th>Type</th>   
            <th>Analyst</th>
            <th style="width:120px;">&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($dbArray as $dbRow) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($dbRow->getId()); ?></td>
                <td><?php echo $this->escapeHtml($dbRow->getName()); ?></td>
                <td><?php echo $this->escapeHtml($dbRow->getLevel()); ?></td>
                <td><?php echo $this->escapeHtml($dbRow->getType()); ?></td>
                <td><?php echo $this->escapeHtml($dbRow->getAnalyst()); ?></td>
                <td><a
                        href="<?php
                        echo $this->url($this->router, array(
                            'action' => 'view',
                            'id' => $dbRow->getId()
                        ));
                        ?>">View </a>
                    <a
                        href="<?php
                        echo $this->url($this->router, array(
                            'action' => 'edit',
                            'id' => $dbRow->getId()
                        ));
                        ?>">Edit</a>
                    <a
                        href="<?php
                        echo $this->url($this->router, array(
                            'action' => 'delete',
                            'id' => $dbRow->getId()
                        ));
                        ?>">Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php echo $this->partial('partial/list_bottom.phtml'); ?>