<?php echo $this->partial('partial/delete_top.phtml'); ?>
<div class="panel-body">
    <p>Are you sure that you want to delete?</p>    
    <label>Name:</label> <?php echo $this->escapeHtml($dbArray->getName()); ?> <br>
    <label>Risk ID:</label> <?php echo $this->escapeHtml($dbArray->getEntityId()); ?> <br>
    <label>Type:</label> <?php echo $this->escapeHtml($dbArray->getType()); ?> <br>
    <label>Analyst:</label> <?php echo $this->escapeHtml($dbArray->getAnalyst()); ?> <br>
    <label>Registered:</label> <?php echo $this->dateFormat($dbArray->getCreated(), IntlDateFormatter::LONG, IntlDateFormatter::MEDIUM); ?><br>
    <label>Updated:</label> <?php echo $this->dateFormat($dbArray->getUpdated(), IntlDateFormatter::LONG, IntlDateFormatter::MEDIUM); ?>  

    <?php
    echo $this->partial('partial/delete_bottom.phtml');   